Calls to torch/daml from MLBalance
JCSDA-internal/soca pull request #1016
Opened 2024-02-13 23:54 UTC by guillaumevernieres

## Description
It is still a plumbing PR, absolutely zero science yet. The results from the 3dvar test are pretty bad, but I'm blaming this on:
- The nn being trained on a 1/4 deg ocean/ice background and for a different season.
- I invented values for the missing variables
- the diag of B is 1 for all variables ... 

**Work done:** 
- MLBalance is only built and tested if `daml` and `torch` are found
- Use of the gradient of the ice emulator from `daml` to initialize the Jacobian in `MLBalance`.
- git-lfs storage of the weights as binary files for the 2 poles. They came from training the nn with a 1/4 deg background. The gradient of the emulator looks reasonable when the inference is done at the same resolution and with a background close enough to the training date ... probably clear as mud. 
- I invented the background for the missing variables (Tair, Tsfc and sice) and updated the `cice` restart/background file 

### Issue(s) addressed
- fixes #1015 

## Testing

How were these changes tested?  **a dirac and a 3dvar test were added**
What compilers / HPCs was it tested with?  **gnu only**
Are the changes covered by ctests? **Yes and no, mlbalance and it associated tests are only tested if daml/torch are found**

## Dependencies
`torch` & `daml`

2024-02-16 16:58 UTC, travissluka requested changes

2024-02-16 16:58 UTC, travissluka commented on src/soca/MLBalance/MLBalance.cc
> +  geom_.reset(new Geometry(params_.geometry.value(), outerGeometryData.comm()));
Don't create a new geometry.
I think you can pull the data you need from `outerGeometryData.functionSpace()` which has the lat/lon information.

2024-02-16 16:58 UTC, travissluka commented on src/soca/MLBalance/MLBalance.h
> +  std::shared_ptr<Geometry> geom_;
```suggestion
```

see above comment

2024-02-16 16:58 UTC, travissluka commented on src/soca/MLBalance/MLBalanceParameters.h
> +  oops::RequiredParameter<eckit::LocalConfiguration> geometry{"geometry", this};
```suggestion
```

2024-02-16 16:58 UTC, travissluka commented on src/soca/MLBalance/MLBalance.cc
> +  jac_ = util::createFieldSet(xb["tocn"].functionspace(), jacVars, 0.0);
```suggestion
  jac_ = util::createFieldSet(outerGeometryData.functionspace(), jacVars, 0.0);
```

2024-02-16 16:58 UTC, travissluka commented on src/soca/MLBalance/MLJac.h
> +    }
why is this needed?

2024-02-16 19:30 UTC, guillaumevernieres commented on src/soca/MLBalance/MLJac.h
> +    }
left over from trial and error probably ... I'll remove.

2024-02-17 16:27 UTC, guillaumevernieres commented on src/soca/MLBalance/MLBalance.cc
> +  geom_.reset(new Geometry(params_.geometry.value(), outerGeometryData.comm()));
removed and using `functionsSpace.lonlat()` instead.

2024-02-28 16:32 UTC, travissluka commented
oops, I added conflicts!

2024-03-12 15:36 UTC, shlyaeva commented
I've been "ignoring" this because I saw there were some comments from Travis and some conflicts; let me know when ready for review.

2024-03-12 20:53 UTC, guillaumevernieres commented
> I've been "ignoring" this because I saw there were some comments from Travis and some conflicts; let me know when ready for review.

It's ready to review @shlyaeva . I don't think the ci failures are related to this work.

2024-03-12 21:31 UTC, travissluka commented on test/CMakeLists.txt
> +soca_add_test( NAME 3dvar_godas
@guillaumevernieres bad merge of develop. check this file again and put some things back the way they were

2024-03-13 18:27 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +soca_add_test( NAME 3dvar_godas
Just fixed yesterday's sloppy merge.

2024-03-15 18:13 UTC, travissluka requested changes
minor change request.
For the record though, I don't like the dependency on `daml`. I would like that eliminated once we have torch part of spack stack and are able to exercise this stuff in our CI

2024-03-15 18:13 UTC, travissluka commented on test/CMakeLists.txt
> +  testinput/3dvar_godas.yml
```suggestion
```

2024-03-15 18:13 UTC, travissluka commented on test/CMakeLists.txt
> +                              test_soca_parameters_diffusion_vt)
```suggestion
                              test_soca_parameters_diffusion )
```

2024-03-15 18:13 UTC, travissluka commented on test/testinput/3dvar_diffmlb.yml
> +  datadir: data_generated/3dvar_diffmlb
```suggestion
  datadir: data_output/
```

2024-03-15 18:13 UTC, travissluka commented on test/testinput/3dvar_diffmlb.yml
> +        datadir: data_generated/3dvar_diffmlb
```suggestion
        datadir: data_output/
```

2024-03-15 18:13 UTC, travissluka commented on test/testinput/3dvar_diffmlb.yml
> +            obsfile: data_generated/3dvar_diffmlb/icec.3dvar_diffmlb.nc
```suggestion
            obsfile: data_output/icec.3dvar_diffmlb.nc
```

2024-03-15 18:13 UTC, travissluka commented on test/CMakeLists.txt
> +  testinput/3dvar_godas.yml
still a sloppy merge!

2024-03-15 18:47 UTC, guillaumevernieres commented
> minor change request. For the record though, I don't like the dependency on `daml`. I would like that eliminated once we have torch part of spack stack and are able to exercise this stuff in our CI

Will do. I don't think I have a choice anyway. I'm facing circular dependencies that I don't know how to resolve, other than by migrating the code inside soca.

2024-03-15 22:10 UTC, travissluka approved these changes

2024-03-21 14:33 UTC, shlyaeva approved these changes
Neat!

2024-03-21 14:33 UTC, shlyaeva commented on src/soca/MLBalance/MLBalance.cc
> +                         const eckit::Configuration & config) {
Nitpick: looks like this argument is not used and can be removed.

2024-03-21 14:33 UTC, shlyaeva commented on src/soca/MLBalance/MLJac.h
> +    }
`conf.getSubConfiguration(str)`?

2024-03-22 20:54 UTC, merged