Feature/add structured grid and cmakelist edit
JCSDA-internal/soca pull request #1057
Opened 2024-07-11 18:52 UTC by jrocha22

## Description

(Instructions: this, and all subsequent sections of text should be removed and filled in as appropriate.)
Provide a detailed description of what this PR does.  
What bug does it fix, or what feature does it add?
Is a change of answers expected from this PR?

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #<issue_number>
- fixes JCSDA/soca-bundle/issues/<issue_number>

## Testing

How were these changes tested?
What compilers / HPCs was it tested with?
Are the changes covered by ctests? (If not, tests should be added first.)

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names for the automated TravisCI tests to pass

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on JCSDA/soca-bundle/pull/<pr_number>
- waiting on JCSDA/oops/pull/<pr_number>

2024-07-11 18:54 UTC, CoryMartin-NOAA commented
@jrocha22 can you modify the PR description to fill out the requested items (describe what this adds, how it was tested, etc.)

2024-07-11 19:00 UTC, CoryMartin-NOAA commented on src/mains/ConvertToStructuredGrid.cc
> + * (C) Copyright 2017-2021 UCAR
2024

2024-07-11 19:01 UTC, CoryMartin-NOAA commented
@jrocha22 we should talk about possibly adding a test that exercises this, if @travissluka wants us to add one

2024-07-11 19:30 UTC, travissluka commented
> @jrocha22 we should talk about possibly adding a test that exercises this, if @travissluka wants us to add one

yes, please add a ctest using one of the low res 5 deg files in soca, @jrocha22 let me know if you need guidance on how to add a ctest to soca.

side note: wow, I'm surprised that works with such little code, good job model interface team! (@fmahebert )

2024-07-11 20:51 UTC, jrocha22 commented
> > @jrocha22 we should talk about possibly adding a test that exercises this, if @travissluka wants us to add one
> 
> yes, please add a ctest using one of the low res 5 deg files in soca, @jrocha22 let me know if you need guidance on how to add a ctest to soca.
> 
> side note: wow, I'm surprised that works with such little code, good job model interface team! (@fmahebert )

@travissluka some ctest guidance would be great! thank you

2024-07-18 15:34 UTC, travissluka requested changes
Sorry, I lost track of time, I meant to send you this last week:

For adding a ctest, take a look at the `soca/test/CMakeLists.txt` file. Take a look at the `hofx_3d` test for example. Do a search in that file and you'll see `hofx_3d` in 3 places:
1) The test is added with a `soca_add_test` command here https://github.com/JCSDA-internal/soca/blob/92519ab72b89a4c3b802501e71b7b66349fc8cc8/test/CMakeLists.txt#L597
2) The input yaml file has to have the same name as the test. In this case `testinput/hofx_3d.yaml` and it is added to the cmakelist file here https://github.com/JCSDA-internal/soca/blob/92519ab72b89a4c3b802501e71b7b66349fc8cc8/test/CMakeLists.txt#L58 
3) and last is the output reference file `testref/hofx_3d.yaml` added here https://github.com/JCSDA-internal/soca/blob/92519ab72b89a4c3b802501e71b7b66349fc8cc8/test/CMakeLists.txt#L120 This file is generated by the test itself, and placed in the `testoutput/` directory, I just copy over the file from `testoutput/` to `testref/`, and the test should pass the next time you run it.

If you open `testinput/hofx_3d.yaml`, at the very end you'll see the output and reference files mentioned in 2 and 3 above, here https://github.com/JCSDA-internal/soca/blob/92519ab72b89a4c3b802501e71b7b66349fc8cc8/test/testinput/hofx_3d.yml#L232

I hope that helps

2024-07-29 14:27 UTC, CoryMartin-NOAA commented
Thanks @travissluka , @jrocha22 's summer with us is coming to a close, but either myself or @catherinethomas-noaa will help get this over the finish line with a test if Juliette is unable to

2025-05-08 15:41 UTC, travissluka commented
closing stale PR. can be re-opened if needed

2025-12-12 21:45 UTC, guillaumevernieres commented
~@jrocha22 : Thanks for adding this feature! I added a test to your branch but I don't have the permissions to PR in your fork of `soca`. Can you give me temporary write permissions? I can also just close this and resubmit a PR with your changes.~

2025-12-12 22:02 UTC, guillaumevernieres commented
> ~@jrocha22 : Thanks for adding this feature! I added a test to your branch but I don't have the permissions to PR in your fork of `soca`. Can you give me temporary write permissions? I can also just close this and resubmit a PR with your changes.~

I kept your commits @jrocha22 and submitted a new PR: https://github.com/JCSDA-internal/soca/pull/1212

2025-12-12 22:02 UTC, closed without merging

2025-12-12 22:02 UTC, guillaumevernieres commented
Replaced with this https://github.com/JCSDA-internal/soca/pull/1212