Move the torch based ice emulator to soca
JCSDA-internal/soca pull request #1086
Opened 2024-10-26 15:21 UTC by guillaumevernieres

## Description
- Moved all the AI code from the daml repo to soca 
- Added a training ctest to generate the weights of the emulator instead of storing pre-computed weights
- switched to using `libtorch` from the spack-stack, but it's unfortunately not installed as a cmake package (can't use find_package)

### Issue(s) addressed
- fixes #1014 

## Testing
**How were these changes tested?**
**Are the changes covered by ctests? (If not, tests should be added first.)**
3 ctests: training, dirac and 3dvar
It's missing a ctest for the adjoint ... 

**What compilers / HPCs was it tested with?**
Only works with `gnu`, I have no idea how to build `torch` with intel, and it's also not in the intel spack-stack
Tested on hercules only

2024-10-28 12:05 UTC, guillaumevernieres commented
I broke the `cmake` logic to skip the build of `MLBalance`, oops ... I'll look into it this morning.

2024-11-08 19:54 UTC, shlyaeva commented
I pushed a small change: removed linking daml and renamed variables (removed `_category` from the name); ml tests pass on orion for me when passing -DTorch_ROOT during ecbuild step 🎉

2024-11-12 21:49 UTC, shlyaeva reviewed
Looks good to me, though I haven't played with changing parameters etc yet.
I have a few minor technical suggestions below and I don't mind making those changes myself if you'd like @guillaumevernieres.

I have one scientific question. Application of just this balance operator (K I K^T) to a dirac on ice concentration leads to reasonably looking increments in other variables, but also an increased ice concentration increment (it's no longer 1, but a value larger than 1). With a simple 2x2 matrix math I see why this happens, but it still goes against my naive intuition of what a balance operator should do. Does anyone understand whether that's desired behavior (and why if so)?

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +    explicit BaseEmul(const eckit::Configuration & config, const eckit::mpi::Comm & comm):
nitpick: no need for explicit here and elsewhere for ctors with more than one argument.

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +   public:
nitpick: perhaps these could be private?

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +        TODO(G): Move that to oops log debug?
would be nice to move to debug or info or test log here and elsewhere.

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +        // model_->train();
Perhaps because it has no effect in this case? https://pytorch.org/docs/stable/generated/torch.nn.Module.html#torch.nn.Module.train
(I don't know, just guessing).

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +        std::cout.flush();
would be good to move this to an oops info log and use `std::endl` (doesn't render correctly for me on orion otherwise).

2024-11-12 21:49 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/IceEmul.h
> +      std::vector<float> lat = readCice(fileName, "ULAT");
May be nice to move file open/close outside of this routine so it's only opening file once.

2024-11-13 00:41 UTC, guillaumevernieres commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +        // model_->train();
Ha! yes, you're right. I vaguely remember something about normalizing the input/output using a torch generic method  but I couldn't figure out how to make it work. The normalization is done separately, so that line can probably be deleted.

2024-11-13 00:53 UTC, guillaumevernieres commented on src/soca/MLBalance/KEmul/IceEmul.h
> +      std::vector<float> lat = readCice(fileName, "ULAT");
good catch ... yes. 
Keep in mind that section needs to be re-written. I had access to oops but not soca when I coded this in the `daml` repo. We should leverage the io from soca and eventually add the possibility to read multiple backgrounds.

2024-11-15 22:09 UTC, guillaumevernieres commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +   public:
Damn ... OK. I'll add the get/set functions and switch the data members to private.

2024-11-16 20:51 UTC, guillaumevernieres commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +        std::cout.flush();
I switched to oops::Log , it seems to render properly for me ...

2024-11-18 18:23 UTC, travissluka requested changes

2024-11-18 18:23 UTC, travissluka commented on CMakeLists.txt
> +find_package( NetCDF REQUIRED COMPONENTS Fortran C CXX)
@guillaumevernieres The infra team was previously nagging us to get rid of dependency on the C++ bindings of NetCDF (The only remaining repo was soca-science), as it is not well supported by the netcdf people. Please switch to the C bindings instead, I don't want to add the C++ bindings to soca.

2024-11-18 23:53 UTC, guillaumevernieres commented on CMakeLists.txt
> +find_package( NetCDF REQUIRED COMPONENTS Fortran C CXX)
Done (pending ci status), but it's ugly. It took me a while to realize that the c netcdf binding doesn't deal with degenerate dimension implicitly, ouch.
@travissluka , @shlyaeva , don't get too worked up with the `prepData` function. I'll re-write this from scratch next time I work on this project.

2024-11-19 20:57 UTC, shlyaeva approved these changes
Thank you for addressing my comments! I agree, some code can be further improved, but OK with me to do that later.

2024-11-19 20:57 UTC, shlyaeva commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +    void setModel(const std::shared_ptr<Net> & model) { model_ = model; }
I don't think you need any of the setters (which is what I was hoping for!).

2024-11-19 21:41 UTC, guillaumevernieres commented on src/soca/MLBalance/KEmul/BaseEmul.h
> +    void setModel(const std::shared_ptr<Net> & model) { model_ = model; }
Oops. Good catch. Removed.

2024-11-20 15:35 UTC, travissluka approved these changes

2024-11-23 00:03 UTC, merged

2024-12-27 23:05 UTC, shlyaeva commented
> I have one scientific question. Application of just this balance operator (K I K^T) to a dirac on ice concentration leads to reasonably looking increments in other variables, but also an increased ice concentration increment (it's no longer 1, but a value larger than 1). With a simple 2x2 matrix math I see why this happens, but it still goes against my naive intuition of what a balance operator should do. Does anyone understand whether that's desired behavior (and why if so)?

Following up on my question to close this thread. Here, balance operator transforms ice concentration into the balanced and unbalanced parts. The Identity covariance used in the simplified dirac test corresponds to a diagonal matrix with variance of the temperature error and variance of the _unbalanced_ ice concentration error on the diagonal (both equal to 1). Variance of the total ice concentration error (total here == balanced + unbalanced) is higher and not equal to one, so this result is expected. Good explanation of balance operators [for ocean] in [Weaver et al's ECMWF tech memo 491](https://www.ecmwf.int/sites/default/files/elibrary/2006/13007-multivariate-balance-operator-variational-ocean-data-assimilation.pdf).