Splitting TL and NL getvalue
JCSDA-internal/soca pull request #131
Opened 2019-05-20 23:56 UTC by guillaumevernieres

PR 1 of 3 (or more) on imposing bounds to the analysis (epic #128 ):

- Separation of NL and TL getvalue, which wasn't required when no change of variables were applied.

- Minor code cleanup

closes #125

2019-05-30 14:03 UTC, aerorahul commented on src/Fields/soca_interpfields_mod.F90
> +    type(ufo_geovals),             intent(inout) :: geovals
rename geovals to something else.
L263 refers `geovals%geovals(ivar)`

2019-05-30 14:04 UTC, aerorahul commented on src/Fields/soca_interpfields_mod.F90
> +               &incr3d(isc:iec,jsc:jec,1)
Please add case default that will abort or trap an error if unrecognized argument.

2019-05-30 14:48 UTC, aerorahul requested changes
@guillaumevernieres 1st set of comments. I will continue reviewing.

2019-06-04 13:11 UTC, guillaumevernieres commented
@aerorahul & @travissluka : Anychance you could review that pr? If not I will merge by the end of the day.

2019-06-04 20:18 UTC, travissluka approved these changes

2019-06-04 20:21 UTC, aerorahul approved these changes
changes look good.
all tests run as expected.

2019-06-04 20:23 UTC, merged