Draft - Added depth GeoVaL
JCSDA-internal/soca pull request #175
Opened 2019-08-14 18:53 UTC by ShastriPaturi

Added a depth GeoVaL with help from @guillaumevernieres.
Tested the GeoVaL on ADT.

2019-08-14 23:02 UTC, guillaumevernieres requested changes
@ShastriPaturi : Of course we all want @flampouris to do our work, all of it, but perhaps you meant to put him as a reviewer? ;)

3dvarsoca is failing

PS: This doesn't look like a draft PR, when  you submit, there's a green tab that will give you the choice for a pr or a draft pr. Keep it that way though, I'd be OK merging once you fix the issue.

2019-08-15 00:31 UTC, travissluka commented on src/soca/Fields/soca_interpfields_mod.F90
> +       case ("sea_water_depth")
we are trying to stick with the CF conventions wherever possible
http://cfconventions.org/Data/cf-standard-names/67/build/cf-standard-name-table.html
in which case instead of `sea_water_depth` we should use `sea_floor_depth`. 
Or, since we are summing the layer thicknesses here, would it technically be `sea_floor_depth_below_sea_surface`? But that one sounds too long.  @guillaumevernieres  thoughts?

2019-08-15 00:31 UTC, travissluka commented on test/testinput/3dvar_soca.yml
> +        ObsDataOut: {obsfile: ./Data/prof.T.out.test.nc}
not that it effects any of the ctests, but why is this line changed here?

2019-08-15 00:33 UTC, flampouris commented
You are fast guys, I was about to start the review.

On Wed, Aug 14, 2019 at 8:31 PM Travis sluka <notifications@github.com>
wrote:

> *@travissluka* commented on this pull request.
> ------------------------------
>
> In src/soca/Fields/soca_interpfields_mod.F90
> <https://github.com/JCSDA/soca/pull/175#discussion_r314136558>:
>
> > @@ -188,6 +188,9 @@ subroutine interp(fld, locs, vars, geoval, horiz_interp, traj)
>         case ("sea_surface_salinity")
>            fld3d(isc:iec,jsc:jec,1) = fld%socn(isc:iec,jsc:jec,1)
>
> +       case ("sea_water_depth")
>
> we are trying to stick with the CF conventions wherever possible
>
> http://cfconventions.org/Data/cf-standard-names/67/build/cf-standard-name-table.html
> in which case instead of sea_water_depth we should use sea_floor_depth.
> Or, since we are summing the layer thicknesses here, would it technically
> be sea_floor_depth_below_sea_surface? But that one sounds too long.
> @guillaumevernieres <https://github.com/guillaumevernieres> thoughts?
> ------------------------------
>
> In test/testinput/3dvar_soca.yml
> <https://github.com/JCSDA/soca/pull/175#discussion_r314137763>:
>
> >
>      - ObsSpace:
>          name: InsituTemperature
> -        ObsDataOut: {obsfile: ./Data/prof.T.out.nc}
> +        ObsDataOut: {obsfile: ./Data/prof.T.out.test.nc}
>
> not that it effects any of the ctests, but why is this line changed here?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JCSDA/soca/pull/175?email_source=notifications&email_token=AB7DH32T6757PXAMENV7JITQESPWPA5CNFSM4ILX4VNKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCBTXCVA#pullrequestreview-275214676>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/AB7DH35742TCF7SVM7GPL6DQESPWPANCNFSM4ILX4VNA>
> .
>

2019-08-15 00:50 UTC, guillaumevernieres commented on src/soca/Fields/soca_interpfields_mod.F90
> +       case ("sea_water_depth")
@travissluka , sea_floor_depth_below_sea_surface is long, but properly describe what is needed in the filter. It only lives in interp and a few yaml files, I think the long name is fine.

2019-08-15 00:56 UTC, guillaumevernieres commented
@ShastriPaturi , just a few changes. You need to update the output file from the 3dvar test, this is what is causing the failure.

2019-08-15 13:36 UTC, ShastriPaturi commented on src/soca/Fields/soca_interpfields_mod.F90
> +       case ("sea_water_depth")
Ok... I will rename
```suggestion
       case ("sea_water_depth")
to```
case ("sea_floor_depth_below_sea_surface"

2019-08-15 15:46 UTC, ShastriPaturi commented
I have changed the variable name to sea_floor_depth_below_sea_surface 
and the output filename to ObsDataOut: {obsfile: ./Data/prof.T.out.nc}

2019-08-15 15:54 UTC, travissluka commented on test/testoutput/3dvar_soca.test.test.out
> +Test     : CostJb   : Nonlinear Jb = 2.528383
this file  should not be in  the git repository

2019-08-15 15:59 UTC, travissluka commented on test/testoutput/3dvar_soca.test
> +Test     : CostJb   : Nonlinear Jb = 2.528383
Something is not right here, most of the contents of this file are now missing

2019-08-15 16:33 UTC, ShastriPaturi commented on test/testoutput/3dvar_soca.test
> +Test     : CostJb   : Nonlinear Jb = 2.528383
The ctest was failing earlier.
So I copied the test/testoutput/3dvar_soca.test.test.out to test/testoutput/3dvar_soca.test.

2019-08-15 16:44 UTC, ShastriPaturi commented on test/testoutput/3dvar_soca.test.test.out
> +Test     : CostJb   : Nonlinear Jb = 2.528383
Removed the file

2019-08-15 17:59 UTC, ShastriPaturi commented
I cloned afresh and the 3dvar_soca ctest passes.

2019-08-15 18:18 UTC, travissluka commented
there is something fishy going on with the test log files for our soca execs. You're missing half of what is supposed to be in the .test file. I'm seeing a related output missing issue with something else I'm working on. Hold off on this PR until I can figure out what's going on.

2019-08-15 18:20 UTC, ShastriPaturi commented
> there is something fishy going on with the test log files for our soca execs. You're missing half of what is supposed to be in the .test file. I'm seeing a related output missing issue with something else I'm working on. Hold off on this PR until I can figure out what's going on.

I have definitely noticed it too

2019-08-16 19:15 UTC, travissluka commented
so that we can continue this PR, @ShastriPaturi you should be good now to merge develop into this branch and then update the `testref/3dvar_soca.test` file. Hopefully the latest oops/develop fixes the issues you were seeing with the test output being cutoff

2019-08-16 19:52 UTC, ShastriPaturi commented
> so that we can continue this PR, @ShastriPaturi you should be good now to merge develop into this branch and then update the `testref/3dvar_soca.test` file. Hopefully the latest oops/develop fixes the issues you were seeing with the test output being cutoff

The test_soca_3dvar_soca_compare ctest fails for me.

2019-08-16 19:55 UTC, ShastriPaturi commented
the testref/3dvar_soca.test file is still the same as before.

2019-08-16 19:57 UTC, guillaumevernieres commented
> the testref/3dvar_soca.test file is still the same as before.

Nice, so you found your problem.

2019-08-16 20:00 UTC, ShastriPaturi commented
> > the testref/3dvar_soca.test file is still the same as before.
> 
> Nice, so you found your problem.

I don't know the solution

2019-08-16 20:18 UTC, ShastriPaturi commented
The git merge develop did not bring in the right file.

2019-08-16 20:33 UTC, travissluka commented
@ShastriPaturi what file are you talking about? all of the reference test output files are now in `testref/` directory. `testoutput/` only contains output logs generated at test runtime.

2019-08-16 20:46 UTC, ShastriPaturi commented
> @ShastriPaturi what file are you talking about? all of the reference test output files are now in `testref/` directory. `testoutput/` only contains output logs generated at test runtime.

After I did git merge develop from the branch, the testref/3dvar_soca.test is the same crappy file like before.

2019-08-19 20:55 UTC, guillaumevernieres commented
@ShastriPaturi : Tests are OK. One more request, before I approve that PR, could you post a plot of the obs and the obs that have been filtered out? (similar to the plot you sent me a few weeks ago).
Thanks.

2019-08-19 21:05 UTC, travissluka approved these changes

2019-08-19 22:06 UTC, guillaumevernieres approved these changes

2019-08-19 22:06 UTC, merged