Feature/horiz filt
JCSDA-internal/soca pull request #191
Opened 2019-09-16 20:39 UTC by guillaumevernieres

Closes #51 

This PR adds horizontal filtering of fields and is implemented as a linear variable change. 

Dependency:
- ~~Branch bugfix/mpp_update_ad from FMS. See  [FMS PR #8](https://github.com/JCSDA/FMS/pull/8) from @jkbk2004 , which fixes a bug in the adjoint of the halo update used by the current mom6 configuration.~~ Now in fms dev-master/ecbuild

Feature added:
- 9-point averaging weighted by great circle distance or a distance defined in ssh (may need to revisit)
- Basic plotting script that replaces the unused plotting scripts that were part of the repo. Will be useful for a visual check of the filter along pe boundaries, periodic boundaries between the 2 north pole and E-W end of the grid. Outputs global and polar stereographic plots.

Testing: 
- Dirac test: Illustration of the smoothing close to the N-pole, at the E-W periodic boundary and in general
- Basic linear transform test

Visual/Example usage of basic plotting: 
`./plt_horiz_fld.py -g ../../../build/soca/test/soca_gridspec.nc -f ../../../build/soca/test/Data/ocn.dirac_horizfilt.an.2018-04-15T00\:00\:00Z.nc -l -.1 .1 -v Temp -c jet`

2019-09-26 17:20 UTC, travissluka commented
@guillaumevernieres I just came across this PR... you never added anyone as reviewers!

2019-09-26 17:25 UTC, guillaumevernieres commented
@travissluka , waiting for the fms pr to be merged before it can be reviewed.

2019-09-29 14:08 UTC, aerorahul commented
Most look good. Will test tomorrow.

2019-09-30 14:43 UTC, travissluka requested changes
I'm getting the following in debug mode
```
The following tests FAILED:                                                      
         21 - test_soca_horizfilt (SEGFAULT)                                     
         32 - test_soca_dirac_horizfilt (Failed)                                 
         33 - test_soca_dirac_horizfilt_compare (Failed)    
```
TravisCI is failing on 21, 33 as well (tolerance issues, not a segfault, but since it's not running in debug it's probably the same problem as I'm seeing)


```
21: At line 119 of file /home/tsluka/work/jedi-soca/soca.src/soca/src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
21: Fortran runtime error: Index '2' of dimension 4 of array 'self%wgh' above upper bound of 1
```
similar messages for 32

2019-10-01 23:05 UTC, guillaumevernieres commented
@travissluka , I don't see the issue with gcc/singularity.

2019-10-03 14:55 UTC, travissluka commented
new bug!

Running in debug and release, all the tests are passing except for the `dirac_horizfilt`. I see it's passing TravisCI, so I'll try to take a look today and figure out why it's failing on just my machine.

```
32: Run: Finishing oops::Dirac<SOCA> with status = 0
32: [rancor:23928] Signal: Segmentation fault (11)
32: [rancor:23928] Signal code: Address not mapped (1)
32: [rancor:23928] Failing at address: 0x38     
32: [rancor:23928] [ 0] /lib/x86_64-linux-gnu/libc.so.6(+0x3ef20)[0x14f012743f20]
32: [rancor:23928] [ 1] /opt/modules/gnu-7.4.0/openmpi-3.1.2/hdf5/1.10.5/lib/libhdf5.so.103(H5T_top_term_package+0x115)[0x14f0042e7203]
32: [rancor:23928] [ 2] /opt/modules/gnu-7.4.0/openmpi-3.1.2/hdf5/1.10.5/lib/libhdf5.so.103(H5_term_library+0x466)[0x14f0040b746d]
32: [rancor:23928] [ 3] /opt/modules/gnu-7.4.0/openmpi-3.1.2/hdf5/1.10.5/lib/libhdf5.so.103(+0x4c2e6)[0x14f0040b82e6]
32: [rancor:23928] [ 4] /opt/modules/gnu-7.4.0/openmpi/3.1.2/lib/libmpi.so.40(ompi_attr_delete_all+0x3b6)[0x14f01345f666]
32: [rancor:23928] [ 5] /opt/modules/gnu-7.4.0/openmpi/3.1.2/lib/libmpi.so.40(ompi_mpi_finalize+0x64)[0x14f013482554]
32: [rancor:23928] [ 6] /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/../lib/libeckit_mpi.so(_ZN5eckit3mpi8Parallel8finalizeEv+0x41)[0x14f0092526c1]
32: [rancor:23928] [ 7] /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/../lib/libeckit_mpi.so(_ZN5eckit3mpi8ParallelD1Ev+0x69)[0x14f009252759]
32: [rancor:23928] [ 8] /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/../lib/libeckit_mpi.so(_ZN5eckit3mpi8ParallelD0Ev+0x9)[0x14f0092527a9]
32: [rancor:23928] [ 9] /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/../lib/libeckit_mpi.so(_ZN5eckit3mpi16finaliseAllCommsEv+0x4a)[0x14f0092474ea]
32: [rancor:23928] [10] /home/tsluka/work/jedi-soca/soca.build/gcc_7.4/openmpi_3.1.2/debug/bin/../lib/liboops.so(_ZN4oops3RunD1Ev+0x24)[0x14f013e67a24]
32: [rancor:23928] [11] /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_dirac.x(main+0x60)[0x5571aaabf820]
32: [rancor:23928] [12] /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xe7)[0x14f012726b97]
32: [rancor:23928] [13] /home/tsluka/work/jedi-soca/soca.build/debug/bin/soca_dirac.x(_start+0x2a)[0x5571aaabf88a]
```

2019-10-03 17:20 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +             self%wgh(i,j,ii,jj) = 0.0_kind_real
ah ha, here's your bug. `ii` is actually initialized to `2` from some other previous do loop. Memory corruption occurring. It's funny that valgrind didn't catch this for me, had to find this one manually.

2019-10-03 17:33 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +             self%wgh(i,j,ii,jj) = 0.0_kind_real
Ouch, good catch! An other unfortunate copy/paste.

2019-10-03 18:02 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +             self%wgh(i,j,ii,jj) = 0.0_kind_real
Btw @travissluka , I was getting the same error with the new container. Just pushed a fix.

2019-10-03 18:12 UTC, travissluka requested changes

2019-10-03 18:12 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +    do i = self%isc, self%iec
I'm sure it makes minimal difference to performance, but all your i/j loops should be switched. In Fortran you want the left most dimension of array access to change the fastest

2019-10-03 18:12 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                case ("flow")
For the sake of testing completeness, any chance of adding another test for the `flow` method? the other variables beyond `tocn` as well?

2019-10-03 18:12 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +    do i =  self%iec, self%isc, -1
switch these loops too

2019-10-03 18:12 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +    do i = self%isc, self%iec
switch these loops too

2019-10-03 18:17 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +    do i = self%isc, self%iec
feel free to ignore the loop order for now. I guess I hadn't been paying attention because everything in soca is the opposite order. I'm interested to find out how many nanoseconds  of performance increase we get for 1/4 deg if I re-order all the loops in soca

2019-10-03 18:22 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +    do i = self%isc, self%iec
I wondered why you had never complained about my loops ...

2019-10-03 18:31 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                case ("flow")
will do

2019-10-03 19:57 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                case ("flow")
Got lazy and mixed both method in the same test, with a bit more variable diversity.

2019-10-03 19:59 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                case ("flow")
@travissluka  ... and of course i forgot to update the ref test ... fix coming. oops.

2019-10-04 19:16 UTC, travissluka commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                end select
There should be a default case that aborts the program. Right now if I put a nonsense name into the `filter_type` section of the yaml file the program caries on doing who knows what for math.

2019-10-04 19:46 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                end select
Arg! OK, will add error trap.

2019-10-04 20:12 UTC, guillaumevernieres commented on src/soca/Transforms/HorizFilt/soca_horizfilt_mod.F90
> +                end select
@travissluka , added a trap on the "c side" ... Nothing to do with fishing.

2019-10-04 20:20 UTC, travissluka commented
...I'm making some proposed changes to how the weights are being calculated, sorry. The scale length isn't working the way I think you're expecting it to work. I have to check my math after I get home, but I'll do a PR into your branch this evening

2019-10-07 22:54 UTC, travissluka commented
@guillaumevernieres ok, should be good to go as soon as the travis ci tests pass

2019-10-07 23:24 UTC, guillaumevernieres commented
@travissluka , it's actually building! Progress from the last time.

2019-10-07 23:33 UTC, travissluka approved these changes

2019-10-08 01:34 UTC, merged