Add scripts of downloading Cryosat-2 ice observations
JCSDA-internal/soca pull request #209
Opened 2019-10-03 18:31 UTC by YanHao-NOAA

Scripts "source.esa_ice_cryosat.sh" was created to download Cryosat-2 ice observations from ESA ftp site.
In get_obs.sh, only Cryosat GDR (LRM+SAR+SIN) is used. If users want to use LRM, SAR, SIN data separately, those bash lines with LRM, SAR or SIN need to be uncommented.  
Please close #174

2019-10-03 18:47 UTC, aerorahul approved these changes
looks good.
Thanks for adding this source.

2019-10-03 20:18 UTC, guillaumevernieres requested changes
Thanks for doing that, just a minor comment to address.

2019-10-03 20:18 UTC, guillaumevernieres commented on scripts/obs/get_obs.sh
> +    bash source.esa_ice_cryosat.sh GDR $date $output_path
cryosat is not ice concentration, it needs it's own section ## ice freeboar/thickness

2019-10-04 15:05 UTC, YanHao-NOAA commented on scripts/obs/get_obs.sh
> +    bash source.esa_ice_cryosat.sh GDR $date $output_path
Excellent point! Thank you! I changed get_obs.sh to adding section ## ice freeboard/thickness.
But git push can not connect from my home (I tried a few times, this work is on Hera). I will fix this on Monday from my office.

2019-10-05 12:03 UTC, guillaumevernieres approved these changes
:+1:

2019-10-05 14:38 UTC, flampouris commented
The ice script needs a small update, Yan will push it on Monday.

2019-10-08 02:30 UTC, merged