Use of CRTM UFO
JCSDA-internal/soca pull request #259
Opened 2019-11-20 19:05 UTC by guillaumevernieres

## Description
**Oil spill is contained!** None of the atmospheric variables are mentioned anywhere in the code (except yaml files), so far ...
Revisiting aborted [PR#255](https://github.com/JCSDA/soca/pull/255.) ... and more. This feature branch adds the possibility of using the CRTM ufo in hofx3d (not tested yet with hofx):
- Atmospheric geovals are pre-computed (fv3-jedi) and read inside of getvalue
- Ocean surface (just sst for now) is provided by soca through getvalue.

Is a change of answers expected from this PR? **NO but overflow issue in adt hofx. No clue why. @travissluka and @aerorahul said they'll fix it.**

### Issue(s) addressed
- closes #246 
- Partially  addresses #248, #247, #254 

### What's not too flash
The atmospheric "geometry" and "state" are part of the soca geometry. Not pretty but I can't think of a better way that would work.

## Testing
How were these changes tested? **hofx3dcrtm and geometryatm ctest**
What compilers / HPCs was it tested with? **gcc only**
Are the changes covered by ctests? (If not, tests should be added first.) **YES geometryatm test**

## Dependencies
Need the CRTM

2019-11-20 19:21 UTC, travissluka commented
tests are failing because CRTM is not added to travisCI (so, ha, both Travises dont want CRTM).

Let me do a quick PR first that is needed for letting travisCI config set the bundle-wide ecbuild options .... while we continue to debate the merits of requiring CRTM.

I vote for adding in if statements to the cmakelist so that the crtm tests are skipped if crtm is not present (see the way ufo ctests are setup). We'll have crtm on by default on travisci... and off by default on my and @aerorahul 's laptops. everyone wins

2019-11-20 19:24 UTC, travissluka commented
@guillaumevernieres yeah, that hofx is expected to fail on intel. I don't know what i was thinking enabling SIGFPE trap on that given that the model runs for hofx.

2019-11-20 20:30 UTC, travissluka requested changes
after JCSDA/soca/pull/260 gets merged, modify the CMakeLists.txt to wrap the ctests that need CRTM with `if( ${CRTM_FOUND} )`

2019-11-20 22:30 UTC, guillaumevernieres commented
@travissluka I must have screwed up somewhere, the crtm test didn't run. I'll look at it later tonight or tomorrow.

2019-11-20 23:39 UTC, travissluka commented
I think the problem is that soca isn't seeing that crtm is available because it isn't listed as a dependency in the main `CMakeLists.txt`. This doesn't matter if building as a normal bundle since ufo pulls in crtm, but the TravisCI tests build each repo separately.

try adding the line
`ecbuild_use_package( PROJECT crtm VERSION 2.2.3)`

Also, there's probably no harm in leaving the `geometryatm` test enabled even if crtm is not present

2019-11-20 23:57 UTC, guillaumevernieres commented
@travissluka OK, trying again.

2019-11-21 00:10 UTC, travissluka commented on CMakeLists.txt
> +
oooh, double UFO !

2019-11-21 00:20 UTC, travissluka commented
@guillaumevernieres can't find the binary file now... because we aren't building everything as a single bundle. I had the same issue with files from oops, I'll lookup the syntax needed and get back to you...

2019-11-21 00:27 UTC, guillaumevernieres commented
Still no cigar, but closer. Looks like the .bin for the crtm were not found ...  Ha, just seeing your post above.  Nice, thanks for your help.

2019-11-21 00:46 UTC, guillaumevernieres commented on CMakeLists.txt
> +
dang, I knew the copy paste went badly ... Will wait until you send me a solution for the lfs files before pushing the fix.

2019-11-21 02:41 UTC, guillaumevernieres commented
Thanks @travissluka

2019-11-21 03:40 UTC, travissluka requested changes

2019-11-21 03:40 UTC, travissluka commented on CMakeLists.txt
> +include_directories( ${CRTM_INCLUDE_DIRS} )
```suggestion
```

2019-11-21 03:40 UTC, travissluka commented on src/soca/State/State.cc
> +        Log::trace() << cols << std::endl;
remove, or make the output informative

2019-11-21 03:40 UTC, travissluka commented on src/soca/State/State.cc
> +    Log::trace() << cols << std::endl;
same as above

2019-11-21 16:14 UTC, travissluka approved these changes
Less of a Frankenstein than I was expecting 👍 

I tested on intel19 as well and all looks good.

2019-11-21 16:14 UTC, travissluka commented on src/soca/Fields/soca_interpfields_mod.F90
> +     ! TODO: Move unit change elsewhere, check if surface_temperature_where_sea
might want to create a github issue to remind us.... we had discussed before that all of our ocean temp variables should be in K to comply with CF conventions. But of course that requires changing ufo at the same time... a good project for when someone is bored and doesn't want to do real work.

2019-11-21 18:51 UTC, merged