Feature/rotate
JCSDA-internal/soca pull request #301
Opened 2020-03-17 15:20 UTC by guillaumevernieres

## Description
- Addition of a variable change (Ana2Model) to rotate horizontal vectors between Model and State (for now only implemented for (u,v) ). The Model coordinate for velocities is locally defined by the grid. Using the "Ana2Model" variable change will rotate to a zonal/meridional coordinate system.  
- Removed the passing of fields from state to model at every time steps (not needed), this changes the forecast output slightly. 

### Issue(s) addressed
Partially addresses issue #292, #282.

## Testing

How were these changes tested? **Addition of a test for non-linear variable changes** 
What compilers / HPCs was it tested with? **gcc**
Are the changes covered by ctests? **yes**

2020-03-17 15:38 UTC, guillaumevernieres commented
Oops ... No excuses, it even fails on my laptop.

2020-03-17 16:04 UTC, guillaumevernieres commented
First try!

2020-03-17 18:20 UTC, travissluka requested changes

2020-03-17 18:20 UTC, travissluka commented on src/soca/Fields/soca_fields_mod.F90
> +  if (self%has("uocn").and.self%has("vocn")) then
I don't like the hardcoding of "uocn" and "vocn". The pairs of variable names should be configurable in the yaml somwehere, or at the very least at a higher level in the code and passed into this function. 
Granted, we only care about ocean u/v for now, but what about in the future when we have  ice u/v, wave u/v, whale/sea-lion trajectory u/v.... etc

2020-03-17 18:20 UTC, travissluka commented on src/soca/Fields/soca_fields_mod.F90
> +  integer :: z, i
`i` is unused, delete

2020-03-18 14:13 UTC, guillaumevernieres commented on src/soca/Fields/soca_fields_mod.F90
> +  if (self%has("uocn").and.self%has("vocn")) then
@travissluka agreed, but we would need to re-write the "read" routine. For example, we try to get "hocn" at the start of read, without checking if it is part of the list of variables. Not a huge tasks, but I'd rather confine it to its separate issue.

2020-03-18 22:33 UTC, guillaumevernieres commented
@travissluka , as requested, I added the possibility of rotating a pair of fields. A scientifically sound example is in 3dvar_godas and a test with 3 pairs is in the ana2model ctest were we rotate things like (T,S) ... because we can.

2020-03-19 17:51 UTC, travissluka commented
@guillaumevernieres did you happen to do any plotting to visually confirm it's working as intended?

2020-03-19 18:59 UTC, guillaumevernieres commented
@travissluka I dumped the output on the screen as I was putting that thing together, but good point, that's not enough. Let me check/plot.

2020-03-19 19:00 UTC, travissluka commented
ack, we're running with MOM6 settings that keep a rotation bug at the tripolar fold. Look at sin(angle) at the top right
![image](https://user-images.githubusercontent.com/12516201/77104320-75045e00-69e1-11ea-9500-b66361b2b894.png)

2020-03-19 19:05 UTC, travissluka commented
@guillaumevernieres I'll push a PR first that fixes the above sin/cos from MOM6, since that'll change existing answers... should just take me a minute

2020-03-19 19:25 UTC, guillaumevernieres commented
> @guillaumevernieres I'll push a PR first that fixes the above sin/cos from MOM6, since that'll change existing answers... should just take me a minute

Will do. Good catch, again! I was looking at the 1 deg grid (see below), which as the same issue but quite harder to see.
![sinbug](https://user-images.githubusercontent.com/14031856/77106613-c4548980-69f5-11ea-9a64-400fb5ccaecc.png)

2020-03-19 19:40 UTC, travissluka commented
@guillaumevernieres  actually... i'm not doing a separate PR, that bug seems to not affect MOM6 answers (if I remember correctly it does affect SIS2 answers though, so not a concern for us). But to get you the right sin, add these lines to the end of  `test/Data/72x35x25/MOM_input` and rerun the gridgen app

```
USE_TRIPOLAR_GEOLONB_BUG = False
GRID_ROTATION_ANGLE_BUGS = False
```

2020-03-19 23:13 UTC, guillaumevernieres commented
woot ...
![goodsin](https://user-images.githubusercontent.com/14031856/77123152-b44ca200-6a15-11ea-90c3-4a8d214b538c.png)

2020-03-20 16:53 UTC, travissluka approved these changes
If you want to go ahead and merge, so that we can keep up with the Fields changes i'm doing.
We'll make sure it's scientifically correct later.

2020-03-20 17:05 UTC, guillaumevernieres commented
> If you want to go ahead and merge, so that we can keep up with the Fields changes i'm doing.
> We'll make sure it's scientifically correct later.

I'm pretty sure it's fine, but I'll try to think of a test in a different pr.

2020-03-20 17:05 UTC, merged