GetValues and LinearGetValues classes for soca
JCSDA-internal/soca pull request #326
Opened 2020-04-14 15:22 UTC by guillaumevernieres

## Description

Implements changes required by  [oops #514](https://github.com/JCSDA/oops/pull/514). 
Copy/paste/delete (lots of delete!) of @danholdaway 's [fv3-jedi #314](https://github.com/JCSDA/fv3-jedi/pull/314).

Is a change of answers expected from this PR?
NO. Zero diff with the current getvalue implementation in develop. 

### Issue(s) addressed
- closes #312

### Possible issue remaining
Addition of lint directive to pass the code-norm test. cpplint.py complains about non const references [here](https://github.com/JCSDA/soca/blob/aa5232193d1836e5a44d84d85295be4d5bbde85c/src/soca/GetValues/LinearGetValues.h#L60), [here](https://github.com/JCSDA/soca/blob/aa5232193d1836e5a44d84d85295be4d5bbde85c/src/soca/GetValues/LinearGetValues.h#L66) and [here](https://github.com/JCSDA/soca/blob/aa5232193d1836e5a44d84d85295be4d5bbde85c/src/soca/GetValues/LinearGetValues.h#L67). Inherited, from oops, so I don't have the choice of converting to const or pointers. 
Results are zero diff with develop, so ignoring sounds good to me. Could it be hiding an underlying problem?

## Testing

How were these changes tested?
Addition of 2 ctest, one for each class.

What compilers / HPCs was it tested with?
Are the changes covered by ctests? (If not, tests should be added first.)

## Dependencies

- waiting on [oops #514](https://github.com/JCSDA/oops/pull/514)
- waiting on [ufo #822](https://github.com/JCSDA/ufo/pull/822)

2020-04-14 15:47 UTC, shlyaeva commented on src/soca/GetValues/GetValues.cc
> +    // Get atm geovals
An uninvited suggestion: I think the read may be moved to constructor, so it's only called once per H(x) computation; and then in fillGeoVaLs you could just fill in relevant variables for relevant locations from the atmospheric geovals that were read in the constructor.

2020-04-14 15:57 UTC, guillaumevernieres commented on src/soca/GetValues/GetValues.cc
> +    // Get atm geovals
Sounds good. Thanks for looking at it @shlyaeva , I'll address the issue in a different pr, maybe at the same time we add 4d to the atm geovals.

2020-04-14 16:15 UTC, danholdaway commented on src/soca/GetValues/soca_getvalues_mod.F90
> +      ! TODO: Move unit change elsewhere, check if is COARDS.
This could be done in the variable change. We do something similar for Ozone in a variable change.

2020-04-14 16:15 UTC, danholdaway approved these changes

2020-04-14 16:25 UTC, guillaumevernieres commented on src/soca/GetValues/soca_getvalues_mod.F90
> +      ! TODO: Move unit change elsewhere, check if is COARDS.
Yup, it's in the `why do today what can be done tomorrow epic.`

2020-04-14 22:08 UTC, travissluka requested changes
see my nit picking comments . Try to keep only the bare minimum of `#include`s needed in header files, they should be in the `.cc` instead when possible (basically only things that are related to class member variables stay in the `.h`, not things in the class method prototypes). I removed `#include`s that weren't needed, and moved a couple things to forward declarations instead.

2020-04-14 22:08 UTC, travissluka commented on src/soca/GetValues/GetValues.cc
> +
```suggestion
#include "eckit/config/LocalConfiguration.h"

```

2020-04-14 22:08 UTC, travissluka commented on src/soca/GetValues/GetValues.h
> +}
```suggestion
#include "soca/Fortran.h"

#include "oops/util/ObjectCounter.h"
#include "oops/util/Printable.h"

#include "ufo/Locations.h"

// Forward declarations
```

2020-04-14 22:08 UTC, travissluka commented on src/soca/GetValues/LinearGetValues.cc
> +#include "ufo/Locations.h"
```suggestion
#include "oops/util/DateTime.h"
#include "oops/util/Logger.h"

#include "soca/Geometry/Geometry.h"
#include "soca/GetValues/GetValuesFortran.h"
#include "soca/GetValues/LinearGetValues.h"
#include "soca/Increment/Increment.h"
#include "soca/State/State.h"

#include "ufo/GeoVaLs.h"
#include "ufo/Locations.h"
```

2020-04-14 22:08 UTC, travissluka commented on src/soca/GetValues/LinearGetValues.h
> +}
```suggestion
#include <ostream>
#include <string>
#include <memory>

#include "soca/Fortran.h"

#include "oops/util/ObjectCounter.h"
#include "oops/util/Printable.h"

#include "ufo/Locations.h"

// Forward declarations
namespace ufo {
  class GeoVaLs;
  class Locations;
}
namespace soca {
  class Increment;
  class State;
}
```

2020-04-14 22:10 UTC, travissluka commented
also, why the `feature/getvalues-gv` branch and not `feature/getvalues`?? This could be dangerous if something changes in the oops/ufo `getvalues` branch and we think everything is still working when in reality it isn't

also, also... thanks :+1:

2020-04-15 12:41 UTC, guillaumevernieres commented
> see my nit picking comments . Try to keep only the bare minimum of `#include`s needed in header files, they should be in the `.cc` instead when possible (basically only things that are related to class member variables stay in the `.h`, not things in the class method prototypes). I removed `#include`s that weren't needed, and moved a couple things to forward declarations instead.

@travissluka : I did try to move as many as I could to the .cc before submitting this pr. Did you build/test your suggestions? I'll test locally.

2020-04-15 12:44 UTC, travissluka commented
Yes, I did. Would you like me to just push a commit with those?

On Wed, Apr 15, 2020, 6:41 AM guillaumevernieres <notifications@github.com>
wrote:

> see my nit picking comments . Try to keep only the bare minimum of
> #includes needed in header files, they should be in the .cc instead when
> possible (basically only things that are related to class member variables
> stay in the .h, not things in the class method prototypes). I removed
> #includes that weren't needed, and moved a couple things to forward
> declarations instead.
>
> @travissluka <https://github.com/travissluka> : I did try to move as many
> as I could to the .cc before submitting this pr. Did you build/test your
> suggestions? I'll test locally.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JCSDA/soca/pull/326#issuecomment-614014362>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AC7PW2OE6ZK5KPAL3AM2N6TRMWTPVANCNFSM4MH2QD4Q>
> .
>

2020-04-15 12:46 UTC, guillaumevernieres commented
> also, why the `feature/getvalues-gv` branch and not `feature/getvalues`?? This could be dangerous if something changes in the oops/ufo `getvalues` branch and we think everything is still working when in reality it isn't
> 
> also, also... thanks +1

Poor judgement from my side. I forgot exactly what was the issue, I'll keep track of the changes in ufo and oops (yeah right!).

2020-04-15 12:47 UTC, guillaumevernieres commented
> Yes, I did. Would you like me to just push a commit with those?

:+1:  Yes, please do!

2020-04-17 15:26 UTC, travissluka approved these changes

2020-04-17 16:03 UTC, merged