Feature/convert stat
JCSDA-internal/soca pull request #344
Opened 2020-05-05 19:53 UTC by clouden90

## Description
SOCA State Converter

What bug does it fix, or what feature does it add?
This application performs state conversion both horizontally and vertically. A few changes has been made based on the previous comments
.
The major change is now the intermediate grid step is removed. The [mom_diag_remap module](https://noaa-gfdl.github.io/MOM6/APIs/namespacemom__diag__remap.html#a3cfd706c08bbd33ad21b77c6b045a9c5) is used and the re-gridding is done in soca_gridgen step.

Now the application will do conversion based on the following steps:
(0) Pre-processing: run soca_gridgen to convert grid coordinate to z* grid for both source & target grid;
(1) Call soca_convertstate_setup to read pre-computed z* grid and original grid from soca_gridspec  nc file for both source & target grid;  
(2) Call soca_convertstate_change_resol to convert selected state variables (except target grid cell thickness, which has been defined in step (1)) by following steps:
a.	[Vertical remapping](https://mom6.readthedocs.io/en/dev-gfdl/api/generated/modules/mom_remapping.html#f/mom_remapping/remapping_core_h) from source grid to source_z* grid for selected variable;
b.	[Horizontal remapping](https://noaa-gfdl.github.io/MOM6/APIs/namespacemom__tracer__initialization__from__z.html#a5f3dc84eae5f78304c8e366bf80e3afd) from source_z* grid to target_z* grid for selected variable;
c.	Vertical remapping from target_z* grid to target grid for selected variable.

Several Issues:
1.	The horiz_interp_and_extrap_tracer() is the subroutine used for horizontal interpolation in MOM6 . The main problem we cannot directly use horiz_interp_and_extrap_tracer() is that it only supports tracer variables (e.g. T, S), but we need conversion of vector variables in our application.  Also I found that fill_miss_2d may not work properly in the case that grid cell is surrounded by land mask. 

2.	The example of how to use the state converter can be found in test case “test_soca_convertstate” and associated yaml file “convertstate.yml”. This case shows conversion from global domain (5deg) to coarser global grid (generated from test_soca_gridgen_small). I have done several tests to validate the accuracy/performance of the SOCA state converter and the results are well-documented in a separated report.

## Issue(s) addressed
closes #309 

## Testing
How were these changes tested? Updated test_soca_convertstate (Global -> Coarse global grid)
What compilers / HPCs was it tested with? gcc 7.4, Intel 18, Intel 19
Are the changes covered by ctests? Yes

## Dependencies
#341 , #339 and possibly #340, or #340 could be addressed here.
meshgrid and soca_fill_miss_2d will be removed after PR: [Change meshgrid and fill_miss_2d to public #11](https://github.com/JCSDA/MOM6/pull/13)
#348 (future work)

2020-05-05 20:36 UTC, guillaumevernieres commented
@clouden90 , we need a few pr's to go in before we can think about merging that work. @travissluka and I will address #339 (#210 is in review) since this is going to break a few of our change of variables ... I think. Your work should be a little easier to fit in after #210 and #339 to then address and hopefully close #340 and #309, possibly enhancing whatever we'll come up with in #339.
Sounds like a plan?

2020-05-05 21:21 UTC, clouden90 commented
> @clouden90 , we need a few pr's to go in before we can think about merging that work. @travissluka and I will address #339 (#210 is in review) since this is going to break a few of our change of variables ... I think. Your work should be a little easier to fit in after #210 and #339 to then address and hopefully close #340 and #309, possibly enhancing whatever we'll come up with in #339.
> Sounds like a plan?

@guillaumevernieres , sure, it sounds a perfect plan to me. I do see #210 before reopening this draft pull request. This draft PR is mainly for tracking purpose as well as exchanging ideas. I will also take a look #210 and other dependencies to see how I am going to fit in my work.

2020-05-06 14:06 UTC, clouden90 commented
@travissluka , I accidentally removed you from the reviewer's list. Just added you back to keep you in the loop. No need actions now.

2020-05-20 23:26 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +use soca_convert_stats_mod
Typo? convert_state instead of convert_stats

2020-05-20 23:29 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! (C) Copyright 2017-2020 UCAR.
2020-2020 instead of 2017-2020

2020-05-20 23:30 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! ------------------------------------------------------------------------------
I don't think we need the example.

2020-05-20 23:31 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +
state instead of stats? Or maybe you had something else in mind? I'm open to suggestion, but your application is converting a state.

2020-05-20 23:35 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  self%hocn_des = hocn2%val
Why do you need hocn2?

2020-05-20 23:36 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  !
I do cringe here, but I see you point ... But if we do it this way, I do think the intermediate grid resolution should be flexible. Did you contact the GFDL developers by any chance? I feel that this problem has been resolved already.

2020-05-20 23:40 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +
I know we don't have a fortran code norm, but I'm not a big fan of the ; separated 1 liner.

2020-05-20 23:54 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  end if
Sorry, I lost the logic. Why do we return at that point?

2020-05-21 00:01 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +!> Create a 2d-mesh of grid coordinates from 1-d arrays.
No need to copy paste: [please use the mom6 meshgrid](https://github.com/JCSDA/MOM6/blob/84c2432670659e3ca0aadb401a0834595ddac605/src/framework/MOM_horizontal_regridding.F90#L878)

2020-05-21 00:10 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! ------------------------------------------------------------------------------
Same here: This is again too close to [mom6 fill_miss_2d](https://github.com/JCSDA/MOM6/blob/84c2432670659e3ca0aadb401a0834595ddac605/src/framework/MOM_horizontal_regridding.F90#L104)
Making use of MOM_memory.h seems appropriate in this case, although we do need to look closely at what's in that file.

2020-05-21 00:16 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +end subroutine soca_hinterp
Note to self: Lost focus here, need to look in more detail at hinterp.

2020-05-21 00:33 UTC, guillaumevernieres requested changes
@clouden90 , I went through most of the code and left a few comments. Please have a look.

Things that needs to be done before you spend more time on that work:

1. Contact GFDL, or dig into MOM6, it seems to me that this feature already exists.
2. We need two `convert_state` tests: fine -> coarse and coarse -> fine
3. Since we have the exact solution of the 2 tests, we also need to compare the interpolated state to the truth.

That's a lot of work so thanks!

2020-05-21 00:33 UTC, guillaumevernieres commented on test/testref/convertstate.test
> +Test     :      us   min=    0.004462   max=    0.019176   mean=    0.009315
We have the truth output state since it was sub-sampled from the original grid. I wonder if we should use something like nccmp with some tolerances that we'd be happy with. 
@clouden90 , did you compare the output state to the sub-sampled one? Some of the min/max are quite different between the input and output.

Also, we need an other test that converts from coarse to fine resolution, which is actually more appropriate for what you want to be doing ultimately.

2020-05-21 01:21 UTC, clouden90 commented
> @clouden90 , I went through most of the code and left a few comments. Please have a look.
> 
> Things that needs to be done before you spend more time on that work:
> 
> 1. Contact GFDL, or dig into MOM6, it seems to me that this feature already exists.
> 2. We need two `convert_state` tests: fine -> coarse and coarse -> fine
> 3. Since we have the exact solution of the 2 tests, we also need to compare the interpolated state to the truth.
> 
> That's a lot of work so thanks!

@guillaumevernieres , Thanks for the comments. I will have a look. Regarding the horizontal remapping feature, there are two subroutines existed in mom_horizontal_regridding module:
1. [horiz_interp_and_extrap_tracer_record](https://mom6.readthedocs.io/en/dev-gfdl/api/generated/modules/mom_horizontal_regridding.html#f/mom_horizontal_regridding/horiz_interp_and_extrap_tracer_record)
2. [horiz_interp_and_extrap_tracer_fms_id](https://mom6.readthedocs.io/en/dev-gfdl/api/generated/modules/mom_horizontal_regridding.html#f/mom_horizontal_regridding/horiz_interp_and_extrap_tracer_fms_id)

I spent some time on these two subroutines and found that either of them will require certain level of modification to fit our need. Maybe I was wrong. I can re-visit them again to see the possibility.

I think it is a good idea to have two 'convert_state tests', but I am not quite sure the comparison you propose will be an apple-to-apple comparison due to the different remapping algorithms are used. Perhaps we can discuss details offline.

2020-05-21 01:39 UTC, guillaumevernieres commented
@clouden90 : As a sanity check. You'll have a hard time convincing me that we should not compare to the truth when we have it! We don't expect bit reproducibility, but we expect a level of sanity we think we can live with. Makes sense?

2020-05-21 14:31 UTC, clouden90 commented
> @clouden90 : As a sanity check. You'll have a hard time convincing me that we should not compare to the truth when we have it! We don't expect bit reproducibility, but we expect a level of sanity we think we can live with. Makes sense?

@guillaumevernieres : There is no doubt that we should have sanity check to validate the state converter we are developing. The question is how to conduct the check correctly. Please find attached figure and I will use it to explain my point. The attached figure shows SST from original 5-deg dataset (left); truth output (middle, sub-sampling from original dataset); and from state converter (right, bilinear interpolation). Let’s focus on the area with red circle. The original dataset contains two data points, and there is only one data point (middle point between the original data points) in the coarse grid. To me, the value extracted from “truth output” is simply a result of “nearest interpolation”, and the value from “state converter” is the average of original data points. In this case, I do not think it is not fair to compare the results from “state converter” to the one from “truth output” and simply make a conclusion that our “state converter” is wrong! Actually in this case the converter works as it should be and the “truth output” is not really a truth. Again I totally agree with your comments and I am fine with what you proposed (it at least can give us first-order comparison). I am just giving some ideas for a better way of performing the comparison (e.g. comparing domain mass conservation with original dataset maybe?) I hope this explanation will help you to understand my point. Again I truly appreciate your time and comments. Feel free to let me know if you have any other thoughts.
![image](https://user-images.githubusercontent.com/30629225/82569376-280e4680-9b4e-11ea-9a89-60258cbbd0d2.png)

2020-05-21 14:58 UTC, guillaumevernieres commented
@clouden90 : Yup, find a set of metrics that you/we are happy with and use that to unit test the interpolation.

FYI: MOM6 can already 3d interpolate restarts, but according to @travissluka , only at tracer locations. Did you look into that mom6 feature?  I'm not saying this is possible, I'm just wondering if we could make use of already existing features that are part of the libraries we are using in this project.

2020-05-21 17:27 UTC, clouden90 commented
> @clouden90 : Yup, find a set of metrics that you/we are happy with and use that to unit test the interpolation.
> 
> FYI: MOM6 can already 3d interpolate restarts, but according to @travissluka , only at tracer locations. Did you look into that mom6 feature? I'm not saying this is possible, I'm just wondering if we could make use of already existing features that are part of the libraries we are using in this project.

@guillaumevernieres : Thx, I will think about appropriate metrics that we can use to test the interpolation. And thanks for the info. As I mentioned before, I do found an existing feature for horizontal remapping in mom6 for state (T&S) and tracers variables but it's not quite fit to what we need because it requires input source file that contains stat/tracer info:
[horiz_interp_and_extrap_tracer()](https://noaa-gfdl.github.io/MOM6/APIs/namespacemom__tracer__initialization__from__z.html#a5f3dc84eae5f78304c8e366bf80e3afd)

The required inputs are:
subroutine, public mom_tracer_initialization_from_z::horiz_interp_and_extrap_tracer ( 
 character(len=*), intent(in) filename,
 character(len=*), intent(in) varnam,
 real, intent(in) conversion,
 integer, intent(in) recnum,
 type(ocean_grid_type), intent(inout) G,
 real, dimension(:,:,:), allocatable tr_z,
 real, dimension(:,:,:), allocatable mask_z,
 real, dimension(:), allocatable z_in,
 real, dimension(:), allocatable z_edges_in,
 real, intent(out) missing_value,
 logical, intent(in) reentrant_x,
 logical, intent(in) tripolar_n,
 logical, intent(in), optional homogenize
  )
You can find an example in soca/bundle/mom6/src/initialization/MOM_state_initialization.F90; LINE:2132

Maybe there are other features but so far this is the one I found.

2020-05-29 17:31 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  self%hocn_des = hocn2%val
hocn2 is target grid cell thickness. We keep it here in case in the future if we have regional mom6 model setup and one would like to use the converted results to hotstart the model directly.

2020-05-29 17:33 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  !
Agree. See description section. Now mom_diag_remap module is used to get zstar grid.

2020-05-29 17:35 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +  end if
hocn has been set in soca_convertstate_setup so skip here.

2020-05-29 17:38 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! ------------------------------------------------------------------------------
I also dislike repeat codes here. Unfortunately they are private subroutines in MOM6 and I have to keep them in this moment. Is there any way to get rid of them besides changing them from private to public?

2020-05-29 19:37 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! (C) Copyright 2020-2020 UCAR.
Replace `stats` with `state` in filename

2020-05-29 19:38 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +
typo: `state` not statse

2020-05-29 19:49 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +        tmp_nz = nz_ !assume geom_src%nzo_zstar == geom%des%nzo_zstar
Not amazingly important, but swap the indices in your loop. I have the same bad habit ...
Why loop outside of the compute domain if you fill the halo after the loop?

2020-05-29 19:53 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +!> Create a 2d-mesh of grid coordinates from 1-d arrays.
Not sure why it's marked as resolved. See above comment, that routine is available in mom6.

2020-05-29 19:57 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! ------------------------------------------------------------------------------
I don't think so. We made a few similar changes in our mom6 fork. I'd rather see a change in mom6 than copy paste of mom6 into soca.

2020-05-29 20:00 UTC, guillaumevernieres commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
why not use the sub-sampled grid?

2020-05-29 21:07 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +! ------------------------------------------------------------------------------
Got your point. Right now I cannot create branch in JSCDA/MOM6, can you add me in so I can make a PR and change meshgrid & fill_miss_2d to public

2020-05-29 21:13 UTC, clouden90 commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
The new test case is more close to "real-world" application (coarse global domain -> fine regional domain). Personally I think it is a better example to show users how the state converter works.

2020-05-29 21:15 UTC, clouden90 commented on src/soca/Utils/soca_convert_stats_mod.F90
> +        tmp_nz = nz_ !assume geom_src%nzo_zstar == geom%des%nzo_zstar
Good catch. That's why we need the second eye! Indeed there is no need +1-1 outside the compute domain.

2020-06-01 13:14 UTC, guillaumevernieres commented
@clouden90 : travis-ci is "broken" for now. It will still fail when fixed though, your mom6 branch name doesn't match this one.

2020-06-01 13:21 UTC, guillaumevernieres commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
I don't think it is since you are loosing access to the "true" state. Does it cover parts of your code that wouldn't be covered otherwise? If yes, then the test is needed, otherwise, remove and revert to using the other grid.

2020-06-01 20:30 UTC, clouden90 commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
Revert back to sub-sample-grid. Again as I replied before, I do not think the truth is really a "truth", it is just another remapping/interpolating method (nearest neighbor interpolation), and it's hard to say which one perform better by direct comparison.

2020-06-01 22:15 UTC, guillaumevernieres commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
I'm open, really, you just need to justify why we need to carry an extra binary file in git-lfs. We spent quite a bit of time reducing the size of our repository, so your argument needs to be a bit more convincing than "I think it's better". You might be right, just make your case, concisely ...

2020-06-02 18:14 UTC, clouden90 commented on test/testinput/convertstate.yml
> +  geom_grid_file: soca_gridspec.regional.nc
> I'm open, really, you just need to justify why we need to carry an extra binary file in git-lfs. We spent quite a bit of time reducing the size of our repository, so your argument needs to be a bit more convincing than "I think it's better". You might be right, just make your case, concisely ...

Will stick with sub-sample-grid for now because it's still a good example and demo. And it's also important to keep the whole package "light". Now I will move to test the new converter with soca-3dvar to check if there is anything else I miss ....

2020-06-04 16:48 UTC, guillaumevernieres commented
@clouden90 , sorry for the travis-ci failures over the last few days. It should work now, please merge develop into your branch and push. If you are working in containers, update your image. It was updated a few days ago.

2020-06-11 18:37 UTC, guillaumevernieres commented on test/Data/72x35x25/input_regional.nml
> + &MOM_input_nml
I thought you got rid of the regional grid?

2020-06-11 18:38 UTC, guillaumevernieres commented on test/testinput/convertstate.yml
> +  variables: &soca_vars [ssh, tocn, socn, hocn, cicen]
What's the issue with the velocities?

2020-06-11 18:39 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_state_mod.F90
> +    call MOM_error(FATAL, "target nzo_zstar /= source nzo_zstar! Reset maximum depth in target grid MOM_input file and re-run soca gridgen")
use fckit log, checkout the examples throughout this repository or look in fckit.

2020-06-11 18:42 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_state_mod.F90
> +
remove comment

2020-06-11 18:44 UTC, guillaumevernieres commented on src/soca/Utils/soca_convert_state_mod.F90
> +  allocate(self%hocn_src(src%isd:src%ied,src%jsd:src%jed,1:src%nzo))
did you mean to add a comment here? comment or remove `!` ... same below.

2020-06-12 02:50 UTC, clouden90 commented on test/testinput/convertstate.yml
> +  variables: &soca_vars [ssh, tocn, socn, hocn, cicen]
Originally got different answers for velocities with different compilers/platforms. Have fixed this problem and the ctest for converter has been updated with velocity fields.

2020-06-12 14:48 UTC, guillaumevernieres commented on src/soca/State/soca_state.interface.F90
> +    if (size(fld%geom%lon,1)==size(rhs%geom%lon,1) .and. size(fld%geom%lat,2)==size(rhs%geom%lat,2) .and. &
That's fine for now, I was supposed to add the "==" operator in geometry,and I didn't. See issue #348 that I conveniently closed without doing the work!
We can imagine cases for which the condition above is not sufficient. OK for this PR, but update the comment above to:
! TODO (Guillaume or Travis) implement == in geometry
or something to that effect.

2020-06-12 14:50 UTC, guillaumevernieres commented on test/testinput/convertstate.yml
>  inputresolution:
:+1:

2020-06-12 14:59 UTC, guillaumevernieres reviewed
All good besides minor comments. I revived issue #348 which I was suppose to address for your work and I didn't ... But we'll need to revisit in the future since only checking the size of the domain isn't good enough to figure out if 2 geometries are the same ... Subject of an other PR, "soon".

2020-06-12 15:36 UTC, guillaumevernieres approved these changes

2020-06-12 19:50 UTC, merged