Included Chl to soca state as a generic tracer
JCSDA-internal/soca pull request #351
Opened 2020-05-08 19:15 UTC by liuxiao37k

## Description

This PR included necessary changes in soca_fields_mod.F90, CMakelists.txt, and the soca test folder to include chlorophyll to soca state as generic tracer. At a first step, chlorophyll is only read from an external file (MOM.res.nc) and not retrieved from the simulated field in mom6/ocean_bgc.

Chlorophyll ('chl') is added to forecast_identity ctest.

## Issue(s) addressed
closes #349 

## Testing

All soca ctests passed on Hera.

## Dependencies
None

2020-05-08 19:30 UTC, liuxiao37k commented
I closed the old PR (https://github.com/JCSDA/soca/pull/335) but kept the feature/ocean_bgc branch as it involves ongoing development to allow chlorophyll values to be passed between soca and mom6/BLING.

2020-05-12 18:47 UTC, guillaumevernieres requested changes
@liuxiao37k : Some left over from your draft pr that needs to be cleaned up.

2020-05-12 18:47 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +  testinput/forecast_mom6_bgc.yml
This test isn't needed just yet. Move Chl to the **forecast_identity.yml** test

2020-05-12 18:47 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +  testref/forecast_mom6_bgc.test
Same comment as above and adjust testref/forecast_identity.test

2020-05-12 18:47 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +  Data/Obs/viirs_jpss1_oc_l2.nc
modis and viirs are not needed yet, remove.

2020-05-12 18:47 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +
same comment as above. Test not needed yet

2020-05-12 18:53 UTC, guillaumevernieres commented
@liuxiao37k , that work is ready to review/merge after you address a few minor issues, then you can move on to working on modis/viirs ufo.

2020-05-18 15:06 UTC, liuxiao37k commented
@guillaumevernieres thanks for the comments. updated as asked. Once this is confirmed and merged, I will push a new branch with chl hofx that has been developed.

2020-05-18 16:32 UTC, guillaumevernieres approved these changes
Thanks @liuxiao37k

2020-05-18 16:33 UTC, merged