log() and exp() transformations
JCSDA-internal/soca pull request #476
Opened 2020-10-26 20:01 UTC by liuxiao37k

## Description

Some ocean variables (e.g. chlorophyll) are always positive and reasonably follow a log-normal distribution on a global-scale. Logarithmic (forward) and exponential (inverse) transformations are thus needed when assimilating these variables in order to 1) normalize the data, and 2) avoid creating negative values after applying the increments.

This PR adds a new "variable change" option within Ana2Model SOCA to apply logarithmic (forward) and exponential (inverse) transformations to a set of variables that need such transformations. varchange_ana2model.yml is updated to test this new feature.

### Issue(s) addressed
- fixes #475 

## Testing
- compiled and tested on Hera

2020-10-26 20:24 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
0.001 seems large?

2020-10-26 20:24 UTC, guillaumevernieres commented on src/soca/Transforms/LogExpon/CMakeLists.txt
> +soca_target_sources(
Not needed for this PR

2020-10-26 20:25 UTC, guillaumevernieres commented on src/soca/Transforms/LogExpon/LogExpon.cc
> +/*
Same here, not needed

2020-10-26 20:25 UTC, guillaumevernieres commented on src/soca/Transforms/LogExpon/LogExpon.h
> +/*
... and this file too needs to go.

2020-10-26 20:28 UTC, guillaumevernieres commented
@liuxiao37k seems fine again at quick glance. I have a few minor comments mostly about removing left over files from your other work.

2020-10-26 23:27 UTC, liuxiao37k commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
> 0.001 seems large?

I chose 0.001 to be consistent with the QC-ed observations (globally, chlorophyll mean is around 0.1 and I'd like to set the maximum to be 10 and minimum to be 0.001 such that the log transformed values center around the mean of 0.1). I agree that mathematically it's less accurate but I am worried that having some data points of log(0.0001)=-9.21 will introduce a large bias to the increments, but I guess it also depends on how we define error functions for transformed data.

2020-10-26 23:40 UTC, liuxiao37k commented
> @liuxiao37k seems fine again at quick glance. I have a few minor comments mostly about removing left over files from your other work.

Oops sorry I forgot to delete the un-needed files. Updated, but some soca tests failed (not ana2model). Seem to be unrelated to the feature branch. Thanks!

2020-10-27 00:26 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
If you have a min and a max, you need to use a logit transform, not a log. But if using log, use something like 
x_log = log(x+eps), that should be perfectly invertible, unlike what you currently coded.
The issue is that the tracers that were zero in the model state are now going to be set to a non-zero value, and this is going to be done at least once per DA cycle. I don't think this is what we want to be doing.

2020-10-27 14:49 UTC, guillaumevernieres commented
Could you merge develop in your branch @liuxiao37k ? @travissluka fixed the issue yesterday.

2020-10-27 19:06 UTC, liuxiao37k commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
Thanks. I agree that epsilon is a better option.

2020-10-27 20:35 UTC, guillaumevernieres requested changes

2020-10-27 20:35 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(trn(:,:,z)+epsilon(trn(:,:,z))) * 2.30258509299 * trocn%mask(:,:)
replace by log(trn(:,:,z)+eps) epsilon doesn't need to be an array, and use log, not log10 * 2.3.....

2020-10-27 20:35 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = exp(trn(:,:,z)) * trocn%mask(:,:)
that is not the inverse of what's above.

2020-10-27 20:36 UTC, guillaumevernieres commented
@liuxiao37k not quite there yet. Your inverse is wrong and replace log10 by log.

2020-10-27 20:40 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
> BTW, do you know how we can avoid having the fortran built-in log() function overwritten by oops:log?
Not quite sure what you mean. It's the fortran built in function that is called, nothing to do with oops. What is the issue?

2020-10-27 23:21 UTC, liuxiao37k commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
Here is the issue: when compiling it reports `This name has not been declared as an array or a function.   [LOG]` because `use fckit_log_module, only: log, fckit_log`.

2020-10-28 01:04 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +        trocn%val(:,:,z) = log10(max(trn(:,:,z),0.001)) * 2.30258509299 * trocn%mask(:,:)
Ho, I see, sorry, I'm slow @liuxiao37k ... 
`fckit log` is not used, just remove it. `use fckit_log_module, only: fckit_log` will be fine.

2020-10-28 01:20 UTC, guillaumevernieres requested changes
Getting closer, I swear.

2020-10-28 01:20 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +      trocn%val = log10(trn+epsilon(trn)) * 2.30258509299
I meant declare a real scalar variable, call it `eps` or something meaningful and set it to a small number ... say 1e-6, we can adjust it later. I don't know what the built in epsilon does, but I don't want to know and I don't want to differentiate it, which will be needed in the near future.

2020-10-28 03:34 UTC, liuxiao37k commented on src/soca/State/soca_state_mod.F90
> +      trocn%val = log10(trn+epsilon(trn)) * 2.30258509299
Got it! updated. Thanks!

2020-10-29 00:57 UTC, guillaumevernieres reviewed
... one minor comment. I'll approve after the change.

2020-10-29 00:57 UTC, guillaumevernieres commented on src/soca/State/soca_state_mod.F90
> +    deallocate(trn)
`trn` 's scope is only within that routine, no need to deallocate. Not a big deal, we used to this ... just because, but it became tedious to maintain. You can safely remove that line

2020-10-29 17:07 UTC, guillaumevernieres approved these changes
Thanks @liuxiao37k

2020-10-29 17:09 UTC, merged