Improved analysis.
JCSDA-internal/soca pull request #55
Opened 2019-03-15 15:59 UTC by guillaumevernieres

Better bkgerror, gets rid of some of the questionable values in the 3dvar increment.

2019-03-15 16:33 UTC, aerorahul requested changes
The usual tests fail (for me on my Mac), so thats OK.
changes look good.
minor updates requested.

2019-03-15 16:33 UTC, aerorahul commented on src/Transforms/Balance/soca_balance_mod.F90
> +          self%kst%jacobian(i,j,1:self%kst%nlayers) =  0.0_kind_Real
replace kind_Real with kind_real

2019-03-15 16:33 UTC, aerorahul commented on src/Covariance/soca_covariance_mod.F90
> +    !call soca_struct2unstruct(dx(:,:), geom, tmp_incr)
please remove commented code.

2019-03-15 16:33 UTC, aerorahul commented on src/Covariance/soca_covariance_mod.F90
> +    !call soca_unstruct2struct(dx(:,:), geom, tmp_incr)
same as above. also everywhere else in this PR.

2019-03-15 16:51 UTC, guillaumevernieres commented
@aerorahul : Removed the commented out code. 
@travissluka , @aerorahul : Could you make sure the increment for the 3dvar is reasonable?

2019-03-15 16:54 UTC, aerorahul commented
looking at the 3dvar increment now.

2019-03-15 16:58 UTC, aerorahul commented
There is something bizarre in the maritime continent in the T, S increments. basically, looks fixed.

2019-03-15 17:10 UTC, travissluka commented
@aerorahul plots? everything looks far more reasonable on my runs. 

@guillaumevernieres I'm going to do a quick test with the hgodas SST/ADT obs , at smaller hz correlation scale, to see how it looks now

2019-03-15 17:22 UTC, guillaumevernieres commented
@travissluka : That would be interesting, just remember that the qc does not work with sst yet ...
@aerorahul : There are still issues, but it should not be as unrealistic as what you were getting with what's in develop.

2019-03-15 17:24 UTC, aerorahul approved these changes

2019-03-15 17:25 UTC, travissluka commented
note: i would highly recommend we get in the habit of doing a "squash and merge" for PRs like this (lots of commits but with very little code actually changed)

2019-03-15 17:26 UTC, aerorahul commented
@travissluka Yes. That has been usually true, except for trigger-happy committers.

2019-03-15 17:59 UTC, travissluka requested changes
adt assimilation looks much better now.
BUT sst assimilation is no good. Looked fine before, but now SST obs have no impact due to a surface T bkg error of order 0.01C in the open ocean. Fix my SST DA !

2019-03-15 18:21 UTC, guillaumevernieres commented
@travissluka : The background error is coming from a 9 member ensemble of stand alone mom6, nudged to some climatological sst's. Is there a way to change the nudging time scale? If you use the sst obs file commented out in the yml, you will see a surface increment.

2019-03-15 21:42 UTC, travissluka commented
@guillaumevernieres could we just replace the T bkg err in your variance file with the bkg error that was generated with the old code using the godas method. I'll send some plots this weekend of what happens when I do that with the hgodas obs. It should be good enough that way to carry on and deal with doing things better after the sprint.

2019-03-15 21:45 UTC, guillaumevernieres commented
@travissluka  sure.

2019-03-17 01:49 UTC, guillaumevernieres commented
Closing this PR. I will submit a new one that addresses the same issues as well as the splitting of the bkgerr change of variable in several factories.

2019-03-17 01:49 UTC, closed without merging