Feature/3dvar dumprst
JCSDA-internal/soca pull request #63
Opened 2019-03-21 00:31 UTC by guillaumevernieres

2019-03-21 01:05 UTC, travissluka commented
I'll go ahead and be the jerk who demands non-blank pull request descriptions in the future.

2019-03-21 01:18 UTC, aerorahul reviewed
First glance comments.
Will run tests now.

2019-03-21 01:18 UTC, aerorahul commented on src/Fields/Fields.cc
> +    os << std::endl << "  Resolution = " << nx << ", " << ny
I don't think this is allowed.
Use Log::debug instead or other ways of displaying information, unless this was part of debugging, in which case, needs clean-up.

2019-03-21 01:18 UTC, aerorahul commented on src/Model/Model.cc
> +#include "ModelFortran.h"
Why breaking from convention here?

2019-03-21 01:18 UTC, aerorahul commented on src/Model/soca_model_mod.F90
> +       !TODO: Read file
Is this valid?
An empty else block?

2019-03-21 01:18 UTC, aerorahul commented on src/Model/soca_model.interface.F90
> +  call soca_setup(model)
Ooh, I like this!

2019-03-21 01:18 UTC, aerorahul commented on src/Model/soca_model.interface.F90
> +  call soca_delete(model)
and this.

2019-03-21 01:18 UTC, aerorahul commented on src/Model/soca_model.interface.F90
> +  call soca_prepare_integration(model, flds)
much cleaner.
Should this be soca_initialize_integration to correspond with soca_finalize_integration?

2019-03-21 01:36 UTC, guillaumevernieres commented on src/Model/Model.cc
> +#include "ModelFortran.h"
cleaning up the Fortran.h that's in src

2019-03-21 01:37 UTC, guillaumevernieres commented on src/Model/soca_model_mod.F90
> +       !TODO: Read file
I wondered too, gcc didn't complain. Will try with intel.

2019-03-21 01:41 UTC, guillaumevernieres commented on src/Model/soca_model.interface.F90
> +  call soca_prepare_integration(model, flds)
Yes, left over from copy paste of qg ...

2019-03-21 01:50 UTC, guillaumevernieres commented
@travissluka : Sorry, I forgot:
Addition of an application to checkpoint the model, which cannot be done anymore when running the 3dvar. Our JEDI friends decided to not call the model in the 3dvar cost function anymore. So while a model object is still being constructed, there are no calls to init and finalize (and currently the only way to checkpoint with the analysis in the state). There are other ways to do this, like having state.save() actually dump a full mom6 restart ... But that's not how it is currently done in soca.

2019-03-21 01:52 UTC, guillaumevernieres commented on src/Model/Model.cc
> +#include "ModelFortran.h"
@aerorahul : Do you mean just sticking to Fortran.h?

2019-03-21 02:13 UTC, guillaumevernieres commented on src/Model/soca_model_mod.F90
> +       !TODO: Read file
@aerorahul : Added log comment to fill the block.

2019-03-21 15:56 UTC, travissluka commented on src/Model/soca_model_mod.F90
> +       WRITE(buf,*) 'IO Advance of MOM6: NOT IMPLEMENTED'
write and print statements that are executed on all cores need to go away, eventually . I'm already getting swamped with repetitive log lines on my 8 core machine, and dread the day I do a 720 core run on gaea.

2019-03-21 16:08 UTC, travissluka commented on mains/CheckpointModel.h
> +    static const std::string classname() {return "soca::ErrorCovariance";}
soca::ErrorCovariance ?

2019-03-21 17:18 UTC, guillaumevernieres commented
I'm finding quite a few issues when building with intel17, I'm closing the PR and will resubmit later today. Hopefully.

2019-03-21 23:42 UTC, guillaumevernieres commented
@travissluka , @aerorahul :  The intel fix will be a different pr, since the problem also exist in develop.

2019-03-22 15:47 UTC, travissluka requested changes

2019-03-22 15:47 UTC, travissluka commented on test/testinput/checkpointmodel.yml
> +  ocn_filename: ocn.3dvar.an.2018-04-15T00:00:00Z.nc
```suggestion
  ocn_filename: ocn.3dvarsoca.an.2018-04-15T00:00:00Z.nc
```

2019-03-22 15:47 UTC, travissluka commented on test/testinput/checkpointmodel.yml
> +  ice_filename: ice.3dvar.an.2018-04-15T00:00:00Z.nc
```suggestion
  ice_filename: ice.3dvarsoca.an.2018-04-15T00:00:00Z.nc
```

2019-03-22 15:48 UTC, travissluka commented on test/testinput/checkpointmodel.yml
> +  ocn_filename: ocn.3dvar.an.2018-04-15T00:00:00Z.nc
you should remove your test directory every time before a final make/ctest/push

2019-03-22 15:57 UTC, guillaumevernieres commented on test/testinput/checkpointmodel.yml
> +  ocn_filename: ocn.3dvar.an.2018-04-15T00:00:00Z.nc
yes, I should ...

2019-03-22 18:56 UTC, travissluka approved these changes

2019-03-22 19:06 UTC, merged