Feature/soca letkf localization
JCSDA-internal/soca pull request #636
Opened 2021-09-22 14:41 UTC by weihuang-jedi

Change geometry location from Point2D (lat, lon) to Point3D (lat, lon, dep/alt).
The purpose is that observation can have a 3D position.
This will add new feature in SOCA localization.

We need to make sure that IODA, OOPS, UFO and SOCA all works properly with such change.

- [ ] waiting on JCSDA-internal/oops/pull/1388
- [ ] waiting on JCSDA-internal/ufo/pull/1528
- [ ] waiting on JCSDA-internal/

Dependency:

- [ ] oops
- [ ] ufo
- [ ] ioda

2021-09-22 18:45 UTC, frolovsa commented on src/soca/GeometryIterator/GeometryIterator.cc
> +     << " / " << dep << std::endl;
lets call this depth. both in code and in print.

2021-09-22 18:47 UTC, frolovsa requested changes
Wei, i think we need to support two cases. One case of a 2D iterator (the default) and the second case of 3D iterator. The best way to trigger this change is to add a property to the geometry yaml and geometry object.

2021-11-04 14:20 UTC, frolovsa commented
@weihuang-jedi i cant tag you as a reviewer in this PR. Can you take a look through this code and let me know if you have any feedback?

2021-11-29 19:36 UTC, guillaumevernieres commented on src/soca/GeometryIterator/soca_geom_iter_mod.F90
> +      call abor1_ftn('soca_geom_iter_equals: unknown geom%iterator_dimension')
That reminds me that we've been meaning to add an "==" operator in Geometry for a while ... 
That's quite a few nested ifs. You could remove one level by testing the non-association on line 111 and abort. I would suggest to use "case" for the `iterator_dimension` to make the code more readable, cosmetic at this point and up to you @frolovsa

2021-11-29 19:40 UTC, guillaumevernieres commented on src/soca/GeometryIterator/soca_geom_iter_mod.F90
>    endif
Same as above. I think you could reduce the number of nested if's by using cases, it could just be me but I get easily confused when I see too many if's. Cosmetic again, so up to you.

2021-11-29 19:45 UTC, guillaumevernieres commented on src/soca/Increment/Increment.cc
>      }
Aaaaaa ... Could that be done differently? use "switch/case" maybe?

2021-11-29 19:46 UTC, guillaumevernieres reviewed
@frolovsa ... Lot's of nested if's in your code, any chance you could try to reduce the number of nested levels where you can?

2021-11-29 20:16 UTC, frolovsa commented
> @frolovsa ... Lot's of nested if's in your code, any chance you could try to reduce the number of nested levels where you can?

@guillaumevernieres i agree not a big fan of all the nests. I like your suggestion of re-writing as "switch/case". I will give it a go.

2021-11-29 21:17 UTC, travissluka commented on test/testinput/obslocalization.yml
> +  interator dimension: 2
"interator" ?

2021-11-29 21:17 UTC, travissluka commented on src/soca/GeometryIterator/soca_geom_iter_interface.F90
> +!
There seems to be a problem with your recent merge of `develop`. This file should be named `soca_geom_iter.interface.F90`

2021-11-29 21:17 UTC, travissluka commented on src/soca/Geometry/soca_geom_mod.F90
> +    integer :: isdl, iedl, jsdl, jedl, ksdl, kedl
can we get rid of all these `k***` variables and just use `1` and `nco` instead? They're redundant

2021-12-01 18:32 UTC, frolovsa commented on src/soca/Geometry/soca_geom_mod.F90
> +    integer :: isdl, iedl, jsdl, jedl, ksdl, kedl
done

2021-12-01 18:32 UTC, frolovsa commented on src/soca/GeometryIterator/soca_geom_iter_interface.F90
> +!
removed this file.

2021-12-01 18:32 UTC, frolovsa commented on test/testinput/obslocalization.yml
> +  interator dimension: 2
done

2021-12-01 20:56 UTC, frolovsa commented on src/soca/GeometryIterator/soca_geom_iter_mod.F90
>    endif
switch top level ifs to select/case. Hopefully that twill make code more readable.

2021-12-01 20:56 UTC, frolovsa commented on src/soca/GeometryIterator/soca_geom_iter_mod.F90
> +      call abor1_ftn('soca_geom_iter_equals: unknown geom%iterator_dimension')
switch top level ifs to select/case. Hopefully that twill make code more readable.

2021-12-01 20:57 UTC, frolovsa commented on src/soca/Increment/Increment.cc
>      }
switch top level ifs to select/case. Hopefully that twill make code more readable.

2021-12-01 20:58 UTC, frolovsa commented
@guillaumevernieres , @travissluka i followed up on your suggestions. See if the code is up to snuff now.

2021-12-07 18:52 UTC, frolovsa commented
@guillaumevernieres @travissluka this is ready to re review. see my comment and request from 6 days ago.

2021-12-07 22:28 UTC, frolovsa approved these changes
Not sure if i should be a reviewer on this one since i wrote most of it. But sure, i will approve it.

2021-12-08 14:36 UTC, travissluka commented on src/soca/GeometryIterator/GeometryIterator.cc
> +int GeometryIterator::iteratorDimension() const {
i'm waiting for the ctests to pass on my computer, then i'll merge this PR.
But just as a sanity check, the ctests *should* be using `iteratorDimension()`, right? codecov is complaining that it is not being used, but I suspect it's wrong.

2021-12-08 14:37 UTC, travissluka approved these changes

2021-12-08 14:38 UTC, merged

2021-12-10 17:43 UTC, YongzuoLi commented
@travissluka I now can test LETKF vertical localization, right ? If so, I will use insitu T/S profile to test it.

2021-12-10 17:49 UTC, frolovsa commented
Not yet.
Still need to add an implementation for the vertical localization. Should
be done in a few weeks.

This PR just allows you loop through 3d points instead of 2d points. but
the result will be the same
------------------------------
Sergey Frolov (he/him)
PSL/OAR/NOAA


On Fri, Dec 10, 2021 at 10:43 AM YongzuoLi ***@***.***> wrote:

> @travissluka <https://github.com/travissluka> I now can test LETKF
> vertical localization, right ? If so, I will use insitu T/S profile to test
> it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/JCSDA-internal/soca/pull/636#issuecomment-991168502>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANJCP7TOAE2QGFXERF46XVTUQI35JANCNFSM5ERPYK2Q>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
>

2021-12-10 18:11 UTC, YongzuoLi commented
@frolovsa Thank you. I will wait.