add basic vertical localization
JCSDA-internal/soca pull request #730
Opened 2022-03-30 17:23 UTC by frolovsa

## Description
Introduces two tests for vertical obs localization. 
- test_soca_obslocalization_vertical tests different parts of the vertical localization (different localization function, log transforms, etc)
- test_soca_obslocalizations tests sequential application of horizontal and vertical localization

### Issue(s) addressed

Link the issues to be closed with this PR, whether in this repository, or in another repository.
(Remember, issues should always be created before starting work on a PR branch!)
- fixes #729 

## Testing
Tested on orion using new ctets

## Dependencies
uses matching branch in ufo 
- waiting on JCSDA/ufo/pull/1959

2022-03-30 20:07 UTC, guillaumevernieres commented on test/testinput/obslocalization_vertical.yml
> +geometry:
It's not as slow as your other vertical loc test (~130s), but it's still in the 10s range. Could you try to use the subsampled grid? Pointing to the geometry below should do the trick.
```yaml
geometry:
    geom_grid_file: soca_gridspec.small.nc
    mom6_input_nml: ./inputnml/input_small.nml
    fields metadata: ./fields_metadata.yml
```

2022-03-30 20:46 UTC, frolovsa commented
will do for both
------------------------------
Sergey Frolov (he/him)
PSL/OAR/NOAA


On Wed, Mar 30, 2022 at 2:08 PM Guillaume Vernieres <
***@***.***> wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In test/testinput/obslocalization_vertical.yml
> <https://github.com/JCSDA-internal/soca/pull/730#discussion_r838922702>:
>
> > @@ -0,0 +1,90 @@
> +geometry:
>
> It's not as slow as your other vertical loc test (~130s), but it's still
> in the 10s range. Could you try to use the subsampled grid? Pointing to the
> geometry below should do the trick.
>
> geometry:
>     geom_grid_file: soca_gridspec.small.nc
>     mom6_input_nml: ./inputnml/input_small.nml
>     fields metadata: ./fields_metadata.yml
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/JCSDA-internal/soca/pull/730#pullrequestreview-926662346>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANJCP7TB5ACAOPUFUNLSY63VCSYCRANCNFSM5SCUL7ZQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2022-04-01 15:45 UTC, frolovsa commented on test/testinput/obslocalization_vertical.yml
> +geometry:
@guillaumevernieres i fixed it up for the ctests in this PR. Still having difficulties fixing it for sqrt test. It complains about kmask.nc having wrong dimensions.

2022-04-01 19:59 UTC, travissluka requested changes
one small correction in the cmakelists file
Thanks @frolovsa !

2022-04-01 19:59 UTC, travissluka commented on test/CMakeLists.txt
> +               TEST_DEPENDS test_soca_gridgen
```suggestion
               TEST_DEPENDS test_soca_gridgen_small
```

2022-04-01 19:59 UTC, travissluka commented on test/CMakeLists.txt
> +               TEST_DEPENDS test_soca_gridgen
```suggestion
               TEST_DEPENDS test_soca_gridgen_small
```

2022-04-01 20:05 UTC, travissluka approved these changes

2022-04-19 19:04 UTC, frolovsa commented
@travissluka this should be ready to merge after the UFO PR is merged. 
https://github.com/JCSDA-internal/ufo/pull/1959

2022-04-20 18:06 UTC, rhoneyager commented
The ufo PR is merged.

2022-04-20 18:21 UTC, merged