Feature/parametric b
JCSDA-internal/soca pull request #752
Opened 2022-06-03 18:15 UTC by guillaumevernieres

## Description

This PR enables writing to file the standard deviation of the parametric background error, or your favorite change of variable applied to a unit increment.

Changes:
- Removal of the intermediate "background errors" that were written to hard-coded file names  in `BkgErrFilt` and `BkgErrGodas`. If one wishes to, these can be saved again using the `convertincrement` application and the desiered variable change.
- Added the possibility of generating a unit increment instead of reading from file
- Added a `ctest` that applies `BkgErrFilt` and `BkgErrGodas` to a unit increment and outputs the estimated parametric background error in a filename specified in the yaml configuration

### Issue(s) addressed

- fixes #751 

## Testing

Tested through the added `ctest` inside a container.

2022-06-03 19:53 UTC, guillaumevernieres commented
It seems like we could get rid of the case where we set the increment to zero when reading. It doesn't seem to be used anywhere ... and codecov is screaming ...

2022-06-06 17:56 UTC, travissluka requested changes
small change, remove `TOL` in the cmake.
Feel free to remove the  `iread=0` section, i dont see anywhere it is being used either.

2022-06-06 17:56 UTC, travissluka commented on test/CMakeLists.txt
> +               TOL  2e-5 0
`TOL` is not used anymore, tolerances can be set, if needed, inside the `test` section of the yaml

2022-06-07 16:47 UTC, travissluka approved these changes

2022-06-07 16:47 UTC, merged