CICE initialization
JCSDA-internal/soca pull request #809
Opened 2022-09-20 23:53 UTC by guillaumevernieres

## Description

### Issue(s) addressed

- fixes #<666>

## Testing

How were these changes tested?
What compilers / HPCs was it tested with?
Are the changes covered by ctests? (If not, tests should be added first.)

## Dependencies

If testing this branch requires non-default branches in other repositories, list them.
Those branches should have matching names for the automated TravisCI tests to pass

Do PRs in upstream repositories need to be merged first?
If so add the "waiting for other repos" label and list the upstream PRs
- waiting on JCSDA/soca-bundle/pull/<pr_number>
- waiting on JCSDA/oops/pull/<pr_number>

2022-09-27 17:18 UTC, kbhargava commented
> The de-aggregation is done is 2 different ways, depending on the type of sea-ice:
> 
> * Re-scaling of the background: You already know what this is.
> * Shuffling of the background: You don't really want to know. It does stuff where the background has no sea-ice.

I really like this description

2022-09-27 18:39 UTC, kbhargava approved these changes
Builds and tests run fine on orion.

2022-09-28 14:42 UTC, ShastriPaturi commented
Builds on orion and tests run fine too.
I will test it before approving.

2022-09-28 15:17 UTC, guillaumevernieres commented
> Builds on orion and tests run fine too. I will test it before approving.

@ShastriPaturi Use the `soca-science`  `feature/init-cice` branch, at your own risk ... I'll create a pr in the near future, but that branch isn't quite ready yet. Let me know when you want to test, it's possible that my last few commits "broke" it.

2022-10-14 18:23 UTC, guillaumevernieres commented
Should I use my merge joker on this PR @travissluka ?

2022-10-14 18:24 UTC, travissluka commented
I'll take a look at this after the JCSDA retreat ends this week... I promise

2022-10-14 19:55 UTC, guillaumevernieres commented
Distracting the reviewer with animated gifs:
![seaice](https://user-images.githubusercontent.com/14031856/195930937-268b0ed9-d4cf-4fea-85de-bd88f5330796.gif)

2022-10-17 15:17 UTC, travissluka requested changes
some very small things, otherwise good to go.

I was sold by the distracting graphics!

2022-10-17 15:17 UTC, travissluka commented on .travis.yml
> +    - LIB_REPOS="jedicmake fms gsw mom6 oops saber ioda ufo icepack"
these libs should be roughly in reverse order of how frequently they change. Assuming the caching on TravisCI works (...debatable)  `icepack` should be before `oops` so that it doesn't get rebuilt every time a `jedi` repo changes

2022-10-17 15:17 UTC, travissluka commented on test/CMakeLists.txt
> +               TEST_DEPENDS test_soca_3dvar_godas)
```suggestion
               TEST_DEPENDS test_soca_gridgen
                            test_soca_3dvar_godas)
```

2022-10-17 15:17 UTC, travissluka commented on test/CMakeLists.txt
> +                    TEST_DEPENDS test_soca_3dvar_godas)
```suggestion
                    TEST_DEPENDS test_soca_gridgen
                                 test_soca_3dvar_godas)
```

2022-10-17 15:17 UTC, travissluka commented on test/CMakeLists.txt
> +  file(COPY ${CMAKE_CURRENT_BINARY_DIR}/data_static/72x35x25/restarts/iced.2018-04-15-00000.nc
just double checking, this does have to be copied because "output" files need to already exist to be opened?

2022-10-17 16:46 UTC, guillaumevernieres commented on test/CMakeLists.txt
> +  file(COPY ${CMAKE_CURRENT_BINARY_DIR}/data_static/72x35x25/restarts/iced.2018-04-15-00000.nc
Correct, it's an "output" file.

2022-10-17 23:22 UTC, travissluka approved these changes

2022-10-17 23:22 UTC, merged

2022-10-17 23:36 UTC, guillaumevernieres commented
:tada: