Feature/colocate
JCSDA-internal/soca pull request #847
Opened 2023-02-28 00:37 UTC by guillaumevernieres

### Description
This was supposed to be straight forward, but then it wasn't.

**Stuff fixed/added:**
- State method added/implemented: `tohgrid` (`tocgrid` doesn't do anything yet)
- Renamed `Ana2Model` to `Model2Ana` to make it less confusing. The variable change under `cost function` is expecting a change of variable from the model to the analysis ... Which we coded backward, or maybe we dropped the inverse switch at some point ... I don't know, but it should be fixed now
- I was hopping to just turn on the interp from uv-points to h-points, but it turned out that thing wasn't working. I added a simple interp based on the 6 neighbors of a point. Simple and a lot faster than a kdtree.

### Notes
- I'm backtracking whatever schematics I added to issue #842 , h(x) should be done on the native grid!
- (u,v) increment on the h-grid and interpolated back to the c-grid then added to the background, or fed to mom6 through iau is fine 
- (u, v) state interpolated from h-grid back to c-grid and directly inserted in the restarts at every cycle is a bad idea (interp=diffusion). 
- I'll add the `tocgrid` method later. We plan to use this work to construct our static-**B** and we only need `tohgrid` to do that work.

### Issue(s) addressed
- fixes #842 

### Testing
- Added the `interp` switch ito the `convertstate_changevar` test 
- Tested at 5deg and 0.25deg.

2023-03-02 21:35 UTC, kbhargava commented
Builds fine and the related tests pass on orion. I am going to have a deeper look tomorrow at the files.

2023-03-13 21:54 UTC, kbhargava requested changes
Looks good. This is what the interpolation does in this test case, thought will just put it here. 
![image](https://user-images.githubusercontent.com/22651193/224840777-9cfac10b-011f-42dc-9719-ca614c7896f9.png)

2023-03-13 21:55 UTC, kbhargava approved these changes

2023-03-13 21:58 UTC, kbhargava approved these changes
I accidentally clicked on "request changes" PR oops!

2023-05-12 13:51 UTC, guillaumevernieres commented
Should I just merge this once I resolve the conflicts or do you want to review @travissluka ?

2023-05-12 14:05 UTC, travissluka commented
I'll look at it today, I promise

2023-05-12 17:32 UTC, travissluka commented on src/soca/Utils/soca_utils.F90
> +subroutine soca_stencil_interp(lon_src, lat_src, lon_dst, lat_dst, data, data_out, nn)
fine for now, but I have big dreams of someday removing all our interp code and using what is available from oops.... someday

2023-05-12 17:34 UTC, travissluka approved these changes

2023-05-12 19:04 UTC, merged