Feature/refactor geovals
JCSDA-internal/soca pull request #87
Opened 2019-04-11 21:20 UTC by shlyaeva

This branch is for ufo geovals refactoring, should go with ioda and ufo feature/refactor_geovals.

2019-04-11 21:27 UTC, guillaumevernieres commented
Thanks @shlyaeva , it fixes our current issue with oops develop.

2019-04-11 21:28 UTC, guillaumevernieres approved these changes

2019-04-12 02:29 UTC, aerorahul commented on src/Fields/soca_interpfields_mod.F90
> +          nlocs = geovals%geovals(ivar)%nobs
@shlyaeva  This is the only issue I had during compilation.
`geovals%geovals(ivar)%nobs` should be `geovals%geovals(ivar)%nlocs`

2019-04-12 02:29 UTC, aerorahul requested changes
see comment below.

2019-04-12 11:39 UTC, guillaumevernieres commented on src/Fields/soca_interpfields_mod.F90
> +          nlocs = geovals%geovals(ivar)%nobs
@aerorahul : That's fine, I'm ok waiting for @shlyaeva's ioda/ufo branch to be merged before we merge this one. But since it's a one liner fix to make it work with develop ioda/ufo we could revert to my simple commit and merge that branch today, the fix for when @shlyaeva 's work is merged would then be trivial. Sorry, I should have mentioned to build with develop ioda/ufo.

2019-04-12 14:11 UTC, aerorahul approved these changes

2019-04-23 14:54 UTC, aerorahul commented
@shlyaeva all good from soca side.

2019-05-01 15:31 UTC, aerorahul commented
@shlyaeva I merged `soca::develop` into this branch.  All tests pass (with known exceptions).
Good to go from `soca`-side.  @travissluka or @guillaumevernieres can confirm from their containers before merge to develop.

2019-05-01 15:36 UTC, shlyaeva commented
@aerorahul, thanks a lot!

2019-05-01 15:41 UTC, travissluka approved these changes
looks good, everything (that should pass) passes

2019-05-01 15:43 UTC, merged