Remove discontinuities in the balance op
JCSDA-internal/soca pull request #885
Opened 2023-05-11 23:52 UTC by guillaumevernieres

## Description
This is not going to suddenly massively improve our forecast skills or analysis, but the filtering of the jacobians of the linearized balances was not handled properly. 
What this PR does:
- replaces the box filter to a tanh filter when zeroing out jacobians over part of the water column
- the handling of the min/max limits for dS(T)/dT was wrong (set to 0 instead of the limits). This issue is illustrated [here](https://github.com/JCSDA-internal/soca-science/issues/578), thanks to @hyunsookkim-NOAA for the plot.
- limiting the application of dS/dT to below the mixed layer is also done with the same `tanh` filter
- a slight reorganization of the yaml config for the balance operator, it looks something like this now:
```yaml
       - linear variable change name: BalanceSOCA
        kst:
          dsdtmax: 0.1
          dsdzmin: 3.0e-6
          dtdzmin: 1.0e-6
          nlayers: 999
        ksshts:
          nlayers: 10
        dcdt:
          filename: data_static/72x35x25/dcdt.nc
          name: dcdt
```
where `nlayers` is the index at which the filter = 0.5 ... No parameter to configure the slope.
- A "bit" out of scope for this PR, but I also added a `vanilla` option for the vertical convolution. It's meant to by-pass a chunk of configuration that was meant to confuse people with slight dyslexia ... 

### Issue(s) addressed
- fixes #883 
- fixes #884 

## Testing

How were these changes tested?
- ctest/5deg
- 1/4 deg global
- some earlier versions were tested by @hyunsookkim-NOAA  
What compilers / HPCs was it tested with?
- intel
- gnu
Are the changes covered by ctests? (If not, tests should be added first.)
- yes

## Dependencies
A change of `yaml` config will be necessary in a few downstream repos (soca-sci, gdasapp, ...)

2023-05-12 16:55 UTC, travissluka commented on src/soca/LinearVariableChange/Balance/soca_balance_mod.F90
> +           coef_mld = soca_tanh_filt(layer_depth%val(i,j,k),mld%val(i,j,1))
I know you don't totally agree with how the nemovar balances were implemented, but I believe they set the jacobian to 0 at the surface and linearly interpolate down to the MLD, instead of such a sharp cutoff. Thoughts on trying that (someday?)

2023-05-12 16:55 UTC, travissluka commented on src/soca/LinearVariableChange/VertConv/soca_vertconv_mod.F90
> +  if (self%vanilla) return
whats the point of adding this flag? It's the same effect as setting  `Lz_mld: 0` in the yaml

2023-05-12 17:06 UTC, travissluka commented on test/testinput/3dvar_godas.yml
> +          nlayers: 999
@guillaumevernieres I see several different values of `nlayers` depending on the tests here. What values would you recommend for the real-world config?

2023-05-12 17:37 UTC, guillaumevernieres commented on test/testinput/3dvar_godas.yml
> +          nlayers: 999
@travissluka We need to turn it off for the global until we properly test it and add a high latitude limit. 999 would turn it off. Omitting the kst config in the yaml to turnt kst off might be a better idea.
10 maybe in the hat10?

2023-05-12 18:34 UTC, guillaumevernieres commented on src/soca/LinearVariableChange/Balance/soca_balance_mod.F90
> +           coef_mld = soca_tanh_filt(layer_depth%val(i,j,k),mld%val(i,j,1))
Sure.

2023-05-12 18:35 UTC, guillaumevernieres commented on src/soca/LinearVariableChange/VertConv/soca_vertconv_mod.F90
> +  if (self%vanilla) return
:man_facepalming: 
:ice_cream: ?

2023-05-12 20:09 UTC, travissluka requested changes
Thanks for doing this. 2 minor things, but otherwise looks good. (also, would it be worthwhile to add the capability, someday, to output the jacobians so that we can look at them to help with debugging?)

* remove the `vanilla` stuff and use the existing paramters
* instead of cramming in a `999`, make it so that you can omit `kst` or `ksshts` in the yaml to turn off those sections?

2023-05-12 20:20 UTC, guillaumevernieres commented
> Thanks for doing this. 2 minor things, but otherwise looks good. (also, would it be worthwhile to add the capability, someday, to output the jacobians so that we can look at them to help with debugging?)
> 
> * remove the `vanilla` stuff and use the existing paramters
> * instead of cramming in a `999`, make it so that you can omit `kst` or `ksshts` in the yaml to turn off those sections?

Will do. Thanks for the review @travissluka .

2023-05-19 15:26 UTC, travissluka approved these changes
Thanks, @guillaumevernieres 
Since soca-science CI is currently broken, I'll go ahead and merge this and try to get the associate soca-sci changes merged in later today.

2023-05-19 15:28 UTC, merged