adding soca hofx test for oasim
JCSDA-internal/soca pull request #963
Opened 2023-09-29 16:10 UTC by HamidehGMAO

## Description
we have added a test to run OASIM hofx in soca. the atmospheric and biochemistry fields are set to a reasonable constant value for now. 

### Issue(s) addressed

https://github.com/JCSDA-internal/soca/issues/927

closes #927 

## Dependencies

this needs to be run with the corresponding ufo branch 
https://github.com/JCSDA-internal/ufo/pull/3054

2023-10-02 15:20 UTC, travissluka requested changes

2023-10-02 15:20 UTC, travissluka commented on test/CMakeLists.txt
> +soca_add_test( NAME hofx_oasim_3d
oasim is optional in the bundle. i.e https://github.com/JCSDA-internal/soca/blob/fc4677b5971e555a6859a5e98f646e660d22d0c9/bundle/CMakeLists.txt#L40 . The test should only be enabled if `BUILD_OASIM` is set

2023-10-02 15:24 UTC, travissluka commented on test/testinput/hofx_oasim_3d.yml
> +          obsfile: data_generated/hofx_3d/pace_oasim.hofx_3d.nc
```suggestion
          obsfile: data_generated/hofx_oasim_3d/pace_oasim.hofx_oasim_3d.nc
```

2023-10-02 15:47 UTC, HamidehGMAO commented on test/CMakeLists.txt
> +soca_add_test( NAME hofx_oasim_3d
Right! I will fix it.

2023-10-10 14:51 UTC, travissluka approved these changes

2023-10-10 14:51 UTC, merged